// ruvector-catalog — Technology recommender for the RuVector monorepo
// https://github.com/ruvnet/ruvector

import type {
  Proposal, ProposalMatch, SearchResult, CatalogVersion,
  Phase, IntegrationDifficulty, IntentResult, AudienceLevel,
  ScopeAdvisory, VerticalContext, IndustryVertical,
} from '../types/index.js';
import { CatalogRepository } from '../catalog/repository.js';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

export class ProposalService {
  private repo: CatalogRepository;

  constructor(repo: CatalogRepository) {
    this.repo = repo;
  }

  generate(
    problemStatement: string,
    searchResult: SearchResult,
    projectName = 'unknown',
    intent?: IntentResult,
  ): Proposal {
    const version = this.repo.getVersion();
    const date = new Date().toISOString().split('T')[0];
    const slug = this.slugify(problemStatement);

    const matches: ProposalMatch[] = searchResult.matches.map((m, i) => ({
      rank: i + 1,
      technology: m.technology,
      capability: m.capability,
      score: m.score,
      whyItMatches: this.generateMatchReasoning(
        problemStatement, m.technology.name,
        m.capability.description, m.technology.useWhen,
        intent?.audienceLevel,
      ),
      integrationDifficulty: this.assessDifficulty(m.technology),
    }));

    const topTech = matches[0]?.technology;

    // Build optional V3 fields based on intent
    let scopeAdvisory: ScopeAdvisory | undefined;
    let verticalContext: VerticalContext | undefined;

    if (intent?.intent === 'out-of-scope') {
      scopeAdvisory = {
        verdict: 'out-of-scope',
        message: 'This query falls outside RuVector\'s current scope. RuVector focuses on vector search, HNSW indexing, ML pipelines, and related Rust-based high-performance computing primitives.',
      };
    }

    if (intent?.matchedVertical) {
      const verticalMapping = this.repo.getVertical(intent.matchedVertical as IndustryVertical);
      if (verticalMapping) {
        verticalContext = {
          vertical: intent.matchedVertical,
          regulatoryContext: verticalMapping.regulatoryContext,
          referenceDocuments: verticalMapping.referenceDocuments,
        };
      }
    }

    const proposal: Proposal = {
      id: `RVBP-${date}-${slug}`,
      title: this.generateTitle(problemStatement),
      date,
      projectName,
      catalogVersion: version,
      problemStatement,
      matches,
      integrationPlan: this.buildIntegrationPlan(matches),
      dependencies: this.buildDependencies(matches),
      codeExample: topTech ? this.buildCodeExample(topTech) : '// No matching technologies found',
      risks: this.buildRisks(matches),
      performanceProjections: this.buildProjections(matches),
    };

    if (scopeAdvisory) proposal.scopeAdvisory = scopeAdvisory;
    if (verticalContext) proposal.verticalContext = verticalContext;

    return proposal;
  }

  render(proposal: Proposal, intent?: IntentResult): string {
    const lines: string[] = [];
    lines.push(`# ${proposal.id}: ${proposal.title}`);
    lines.push('');
    lines.push(`**Date**: ${proposal.date}`);
    lines.push(`**Project**: ${proposal.projectName}`);
    lines.push(`**Catalog Version**: ${proposal.catalogVersion.inventoryVersion} (${proposal.catalogVersion.ruvectorCommitShort})`);

    // V3: Intent classification
    if (intent) {
      lines.push(`**Query Intent**: ${intent.intent} (${(intent.confidence * 100).toFixed(0)}% confidence)`);
      lines.push(`**Audience Level**: ${intent.audienceLevel}`);
      if (intent.matchedVertical) {
        lines.push(`**Industry Vertical**: ${intent.matchedVertical}`);
      }
    }

    lines.push('');

    // V3: Out-of-scope advisory (check intent or proposal.scopeAdvisory)
    if (intent?.intent === 'out-of-scope' || proposal.scopeAdvisory) {
      lines.push('---');
      lines.push('');
      lines.push('## Scope Advisory');
      lines.push('');
      lines.push('This query falls outside RuVector\'s current scope.');
      lines.push('RuVector focuses on vector search, HNSW indexing, ML pipelines,');
      lines.push('and related Rust-based high-performance computing primitives.');
      lines.push('');
      lines.push('Consider exploring alternative tools for this use case.');
      lines.push('');
      lines.push('---');
      lines.push(`*Generated by RuVector Catalog v${proposal.catalogVersion.inventoryVersion}*`);
      return lines.join('\n');
    }

    // V3: Vertical framing (check intent or proposal.verticalContext)
    const activeVertical = intent?.matchedVertical ?? proposal.verticalContext?.vertical;
    if (activeVertical) {
      lines.push(`> **${activeVertical.charAt(0).toUpperCase() + activeVertical.slice(1)} Vertical**: Results are filtered and ranked for ${activeVertical} use cases.`);
      lines.push('');
    }

    lines.push('---');
    lines.push('');
    lines.push('## Problem Statement');
    lines.push('');
    lines.push(proposal.problemStatement);
    lines.push('');
    lines.push('## Matched Technologies (ranked by relevance)');
    lines.push('');

    const isNonTechnical = intent?.audienceLevel === 'non-technical' || intent?.audienceLevel === 'executive';

    for (const m of proposal.matches) {
      lines.push(`### ${m.rank}. ${m.technology.name} (score: ${m.score})`);
      lines.push(`- **Crate**: \`${m.technology.crate}\``);
      lines.push(`- **Capability**: ${m.capability.description}`);
      lines.push(`- **Why it matches**: ${m.whyItMatches}`);
      // V3: Non-technical descriptions
      if (isNonTechnical && m.technology.plainDescription) {
        lines.push(`- **Plain description**: ${m.technology.plainDescription}`);
      }
      if (m.technology.complexity) lines.push(`- **Complexity**: ${m.technology.complexity}`);
      if (m.technology.latency) lines.push(`- **Latency**: ${m.technology.latency}`);
      lines.push(`- **Status**: ${m.technology.status}`);
      lines.push(`- **Integration difficulty**: ${m.integrationDifficulty}`);
      lines.push(`- **Deployment targets**: ${m.technology.deploymentTargets.join(', ')}`);
      if (m.technology.useCases.length > 0) {
        lines.push(`- **Use cases**: ${m.technology.useCases.join(', ')}`);
      }
      lines.push('');
    }

    lines.push('## Recommended Integration Plan');
    lines.push('');
    for (const phase of [proposal.integrationPlan.phase1, proposal.integrationPlan.phase2, proposal.integrationPlan.phase3]) {
      lines.push(`### ${phase.name} (${phase.duration})`);
      for (const step of phase.steps) {
        lines.push(`- ${step}`);
      }
      lines.push('');
    }

    lines.push('## Dependencies');
    lines.push('');
    if (proposal.dependencies.length > 0) {
      lines.push('```toml');
      lines.push('# Cargo.toml');
      for (const dep of proposal.dependencies.filter(d => d.type === 'cargo')) {
        lines.push(`${dep.name} = "${dep.version ?? '*'}"`);
      }
      lines.push('```');
    }
    lines.push('');

    if (!isNonTechnical) {
      lines.push('## Code Example');
      lines.push('');
      lines.push('```rust');
      lines.push(proposal.codeExample);
      lines.push('```');
      lines.push('');
    }

    if (proposal.risks.length > 0) {
      lines.push('## Risks and Mitigations');
      lines.push('');
      for (const risk of proposal.risks) {
        lines.push(`- **Risk**: ${risk.description}`);
        lines.push(`  **Mitigation**: ${risk.mitigation}`);
      }
      lines.push('');
    }

    if (proposal.performanceProjections.length > 0) {
      lines.push('## Performance Projections');
      lines.push('');
      lines.push('| Metric | Current | Projected | Source |');
      lines.push('|--------|---------|-----------|--------|');
      for (const p of proposal.performanceProjections) {
        lines.push(`| ${p.metric} | ${p.current ?? 'N/A'} | ${p.projected} | ${p.source} |`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push(`*Generated by RuVector Catalog v${proposal.catalogVersion.inventoryVersion}*`);

    return lines.join('\n');
  }

  write(proposal: Proposal, outputDir?: string, intent?: IntentResult): string {
    const dir = outputDir ?? join(process.cwd(), 'docs', 'research');
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    const filename = `${proposal.date}-rvbp-${this.slugify(proposal.title)}.md`;
    const filepath = join(dir, filename);
    writeFileSync(filepath, this.render(proposal, intent), 'utf-8');
    return filepath;
  }

  private slugify(text: string): string {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .trim()
      .replace(/\s+/g, '-')
      .slice(0, 40);
  }

  private generateTitle(problem: string): string {
    const words = problem.split(/\s+/).slice(0, 8).join(' ');
    return words.charAt(0).toUpperCase() + words.slice(1);
  }

  private generateMatchReasoning(
    problem: string, techName: string, capDesc: string,
    useWhen: string | null, audience?: AudienceLevel,
  ): string {
    const parts = [`${techName} provides ${capDesc.toLowerCase()}`];
    if (useWhen) parts.push(`specifically designed for: ${useWhen}`);
    if (audience === 'non-technical' || audience === 'executive') {
      parts.push('(in plain terms: this tool solves the problem you described)');
    }
    return parts.join('. ');
  }

  private assessDifficulty(tech: { deploymentTargets: string[]; status: string; features: string | null }): IntegrationDifficulty {
    if (tech.status === 'research') return 'hard';
    if (tech.deploymentTargets.includes('wasm') || tech.deploymentTargets.includes('nodejs')) return 'easy';
    if (tech.features && tech.features.includes('distributed')) return 'hard';
    return 'medium';
  }

  private buildIntegrationPlan(matches: ProposalMatch[]): { phase1: Phase; phase2: Phase; phase3: Phase } {
    const top = matches[0]?.technology;
    const secondary = matches[1]?.technology;

    return {
      phase1: {
        name: 'Phase 1: Quick Win',
        duration: '1-2 days',
        steps: top ? [
          `Add \`${top.crate}\` to Cargo.toml dependencies`,
          `Import and initialize ${top.name} with default configuration`,
          `Replace existing implementation with ${top.name} calls`,
          'Run benchmarks to validate improvement',
        ] : ['Evaluate matched technologies and select primary candidate'],
      },
      phase2: {
        name: 'Phase 2: Enhancement',
        duration: '3-5 days',
        steps: secondary ? [
          `Add complementary technology: ${secondary.name} from \`${secondary.crate}\``,
          'Configure HNSW parameters for your data distribution (M, ef_construction, ef_search)',
          'Add monitoring and metrics collection',
          'Write integration tests covering edge cases',
        ] : ['Tune configuration parameters for your specific use case', 'Add error handling and fallback paths'],
      },
      phase3: {
        name: 'Phase 3: Optimization',
        duration: '1-2 weeks',
        steps: [
          'Profile memory usage and optimize batch sizes',
          'Enable SIMD feature flags for your target architecture',
          'Evaluate WASM deployment for edge/browser if applicable',
          'Run load tests and tune concurrency settings',
        ],
      },
    };
  }

  private buildDependencies(matches: ProposalMatch[]): { type: 'cargo' | 'npm'; name: string; version: string | null }[] {
    const seen = new Set<string>();
    const deps: { type: 'cargo' | 'npm'; name: string; version: string | null }[] = [];
    for (const m of matches) {
      if (!seen.has(m.technology.crate)) {
        seen.add(m.technology.crate);
        deps.push({ type: 'cargo', name: m.technology.crate, version: null });
      }
    }
    return deps;
  }

  private buildCodeExample(tech: { name: string; crate: string; capabilityId: string }): string {
    const crateName = tech.crate.replace(/-/g, '_');
    return `use ${crateName}::prelude::*;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Initialize ${tech.name}
    let config = Config::default();
    let instance = ${tech.name.replace(/[\s-]/g, '')}::new(config)?;

    // Use ${tech.name} for your ${tech.capabilityId.replace(/_/g, ' ')} task
    let result = instance.process(&input)?;

    println!("${tech.name} result: {:?}", result);
    Ok(())
}`;
  }

  private buildRisks(matches: ProposalMatch[]): { description: string; mitigation: string }[] {
    const risks: { description: string; mitigation: string }[] = [];
    const hasExperimental = matches.some(m => m.technology.status === 'experimental');
    const hasResearch = matches.some(m => m.technology.status === 'research');

    if (hasExperimental) {
      risks.push({
        description: 'Some recommended technologies have "experimental" status -- API may change',
        mitigation: 'Pin specific versions in Cargo.toml and wrap calls behind an abstraction layer',
      });
    }
    if (hasResearch) {
      risks.push({
        description: 'Research-stage technologies may have incomplete APIs or undocumented edge cases',
        mitigation: 'Use only for prototyping; plan to migrate to production-status alternatives when available',
      });
    }
    risks.push({
      description: 'RuVector submodule adds 1.58M lines to the project checkout',
      mitigation: 'Use shallow clone (--depth 1) and only depend on needed crates via Cargo workspace path',
    });

    return risks;
  }

  private buildProjections(matches: ProposalMatch[]): { metric: string; current: string | null; projected: string; source: string }[] {
    const projections: { metric: string; current: string | null; projected: string; source: string }[] = [];
    for (const m of matches.slice(0, 3)) {
      if (m.technology.latency) {
        projections.push({
          metric: `${m.technology.name} query latency`,
          current: null,
          projected: m.technology.latency,
          source: `${m.technology.crate} benchmarks`,
        });
      }
      if (m.technology.complexity) {
        projections.push({
          metric: `${m.technology.name} complexity`,
          current: null,
          projected: m.technology.complexity,
          source: `${m.technology.crate} docs`,
        });
      }
    }
    return projections;
  }
}
