//! Server Nostr Identity.
//!
//! The VisionClaw server itself holds a Nostr keypair so it can sign server-issued
//! events independently of any human user. This is the cryptographic root for
//!   * kind 30023 — migration approvals
//!   * kind 30100 — BRIDGE_TO promotions (KG → OWL)
//!   * kind 30200 — bead provenance stamps
//!   * kind 30300 — audit records
//!
//! The private key is loaded once at startup from `SERVER_NOSTR_PRIVKEY`
//! (nsec1… bech32 or 64-char hex). In production a missing key is a hard
//! failure: `fail fast, not fail open`. In dev a key may be auto-generated by
//! setting `SERVER_NOSTR_AUTO_GENERATE=true`.
//!
//! The private key is held inside this struct and is **never** logged, never
//! serialised, and never returned from any HTTP handler. Only the public key
//! (hex / npub) is ever exposed.
//!
//! Signing is synchronous in-memory; broadcasting over relays is best-effort
//! and does not gate the caller — the signed `Event` is always returned.

use std::sync::Arc;
use std::time::Duration;

use anyhow::{anyhow, Context as _};
use log::{debug, error, info, warn};
use nostr_sdk::prelude::*;

/// Supported server-signed event kinds.
///
/// Exposed via `GET /api/server/identity` so third parties know which kinds
/// to trust from this server pubkey.
pub const SUPPORTED_KINDS: &[u16] = &[30023, 30100, 30200, 30300];

/// Timeout applied to each relay publish attempt.
const BROADCAST_TIMEOUT: Duration = Duration::from_secs(8);

/// Operational Nostr identity for the server.
///
/// Cheaply `Arc`-cloneable — the only field that is not `Clone` is the
/// optional `nostr-sdk` client, which is held behind `Arc`. The keys are held
/// by value (they are small and `Clone`).
#[derive(Clone)]
pub struct ServerIdentity {
    keys: Keys,
    relay_urls: Vec<String>,
    /// Lazily initialised nostr-sdk client connected to `relay_urls`.
    /// `None` when `NOSTR_RELAY_URLS` is unset — `sign_and_broadcast` degrades
    /// gracefully to `sign_event` in that case.
    client: Option<Arc<Client>>,
}

impl ServerIdentity {
    /// Load the server identity from the process environment.
    ///
    /// # Resolution order
    /// 1. If `SERVER_NOSTR_PRIVKEY` is set (nsec or hex) — use it.
    /// 2. Else if `SERVER_NOSTR_AUTO_GENERATE=true` AND `APP_ENV != production` —
    ///    generate a fresh ephemeral key and log the pubkey (never the privkey).
    /// 3. Else — return an error. In `main.rs` the `?` propagates which aborts
    ///    startup: that is the desired **fail-fast** behaviour.
    ///
    /// Relay list comes from `NOSTR_RELAY_URLS` (comma-separated).
    pub fn from_env() -> anyhow::Result<Self> {
        let privkey_env = std::env::var("SERVER_NOSTR_PRIVKEY")
            .ok()
            .filter(|s| !s.trim().is_empty());

        let is_production = std::env::var("APP_ENV")
            .map(|v| v == "production")
            .unwrap_or(false);

        let auto_generate = std::env::var("SERVER_NOSTR_AUTO_GENERATE")
            .map(|v| v.eq_ignore_ascii_case("true"))
            .unwrap_or(false);

        let keys = match privkey_env {
            Some(raw) => parse_secret_key(&raw)
                .map(Keys::new)
                .context("SERVER_NOSTR_PRIVKEY is set but invalid (expected nsec1… or 64-char hex)")?,
            None => {
                if is_production {
                    return Err(anyhow!(
                        "SERVER_NOSTR_PRIVKEY is required in production \
                         (APP_ENV=production). Refusing to start."
                    ));
                }
                if !auto_generate {
                    return Err(anyhow!(
                        "SERVER_NOSTR_PRIVKEY is not set and \
                         SERVER_NOSTR_AUTO_GENERATE is not true. Refusing to start."
                    ));
                }
                let keys = Keys::generate();
                warn!(
                    "[ServerIdentity] SERVER_NOSTR_AUTO_GENERATE=true — generated \
                     ephemeral keypair (DEV ONLY). pubkey={}",
                    keys.public_key().to_hex()
                );
                keys
            }
        };

        let relay_urls = parse_relay_urls(
            &std::env::var("NOSTR_RELAY_URLS").unwrap_or_default(),
        );

        // NEVER log the private key. Log only the public identity.
        info!(
            "[ServerIdentity] Loaded server identity: pubkey_hex={}, pubkey_npub={}, relays={}",
            keys.public_key().to_hex(),
            keys
                .public_key()
                .to_bech32()
                .unwrap_or_else(|_| "<bech32 failed>".to_string()),
            if relay_urls.is_empty() {
                "(none)".to_string()
            } else {
                relay_urls.join(",")
            }
        );

        Ok(Self {
            keys,
            relay_urls,
            client: None,
        })
    }

    /// Initialise the nostr-sdk client and connect to configured relays.
    ///
    /// Safe to call once at startup **after** the Tokio runtime is live.
    /// If `NOSTR_RELAY_URLS` is empty this is a no-op — publishing is disabled
    /// but signing still works.
    ///
    /// Errors here are logged and **not** fatal: the server must boot even if
    /// all relays are down.
    pub async fn connect_relays(&mut self) {
        if self.relay_urls.is_empty() {
            debug!("[ServerIdentity] No relays configured, skipping client init");
            return;
        }
        let client = Client::new(self.keys.clone());
        for url in &self.relay_urls {
            if let Err(e) = client.add_relay(url).await {
                warn!("[ServerIdentity] Failed to add relay {}: {}", url, e);
            }
        }
        client.connect().await;
        info!(
            "[ServerIdentity] nostr-sdk client connected to {} relay(s)",
            self.relay_urls.len()
        );
        self.client = Some(Arc::new(client));
    }

    /// Test-only constructor: build an identity directly from a secret key
    /// with no relays and no client. Bypasses env var resolution so unit
    /// tests are hermetic.
    #[cfg(any(test, feature = "test-utils"))]
    pub fn for_test(secret_key: SecretKey) -> Self {
        Self {
            keys: Keys::new(secret_key),
            relay_urls: Vec::new(),
            client: None,
        }
    }

    /// Hex (lowercase, 64 char) encoding of the server public key.
    pub fn pubkey_hex(&self) -> String {
        self.keys.public_key().to_hex()
    }

    /// Bech32 `npub1…` encoding of the server public key.
    pub fn pubkey_npub(&self) -> String {
        self.keys
            .public_key()
            .to_bech32()
            .unwrap_or_else(|_| self.keys.public_key().to_hex())
    }

    /// Configured relay URLs (may be empty).
    pub fn relay_urls(&self) -> &[String] {
        &self.relay_urls
    }

    /// Sign a Nostr event with the server keypair.
    ///
    /// `kind` is caller-specified — typically one of [`SUPPORTED_KINDS`]. Any
    /// `u16` is accepted to allow future kinds without changing this signature.
    /// `content` is the JSON payload (caller-serialised); `tags` are attached
    /// verbatim.
    ///
    /// This never touches the network.
    pub async fn sign_event(
        &self,
        kind: u16,
        content: String,
        tags: Vec<Tag>,
    ) -> anyhow::Result<Event> {
        let builder = EventBuilder::new(Kind::Custom(kind), content).tags(tags);
        let event = builder
            .sign_with_keys(&self.keys)
            .with_context(|| format!("sign_event(kind={kind}) failed"))?;
        debug!(
            "[ServerIdentity] Signed kind={} id={} pubkey={}",
            kind,
            event.id,
            event.pubkey.to_hex()
        );
        Ok(event)
    }

    /// Sign an event and best-effort broadcast it to configured relays.
    ///
    /// Broadcast failures are **logged but not returned as errors** — the
    /// signed `Event` is always returned. Callers that care about propagation
    /// can inspect relay state themselves.
    pub async fn sign_and_broadcast(
        &self,
        kind: u16,
        content: String,
        tags: Vec<Tag>,
    ) -> anyhow::Result<Event> {
        let event = self.sign_event(kind, content, tags).await?;

        match &self.client {
            None => {
                debug!(
                    "[ServerIdentity] No client configured; skipped broadcast of kind={} id={}",
                    kind, event.id
                );
            }
            Some(client) => {
                let fut = client.send_event(&event);
                match tokio::time::timeout(BROADCAST_TIMEOUT, fut).await {
                    Ok(Ok(output)) => {
                        info!(
                            "[ServerIdentity] Broadcast kind={} id={} success_relays={} failed_relays={}",
                            kind,
                            event.id,
                            output.success.len(),
                            output.failed.len()
                        );
                    }
                    Ok(Err(e)) => {
                        error!(
                            "[ServerIdentity] Broadcast kind={} id={} failed: {}",
                            kind, event.id, e
                        );
                    }
                    Err(_) => {
                        error!(
                            "[ServerIdentity] Broadcast kind={} id={} timed out after {:?}",
                            kind, event.id, BROADCAST_TIMEOUT
                        );
                    }
                }
            }
        }
        Ok(event)
    }
}

/// Parse either a `nsec1…` bech32 string or a 64-char hex string into a
/// `SecretKey`. Trims surrounding whitespace. Returns `Err` for any other form.
fn parse_secret_key(raw: &str) -> anyhow::Result<SecretKey> {
    let trimmed = raw.trim();
    if trimmed.starts_with("nsec1") {
        SecretKey::from_bech32(trimmed).map_err(|e| anyhow!("nsec decode failed: {e}"))
    } else {
        SecretKey::from_hex(trimmed).map_err(|e| anyhow!("hex decode failed: {e}"))
    }
}

/// Parse a comma-separated list of relay URLs. Empty strings are dropped.
/// Any URL that is not `ws://` or `wss://` is rejected (logged and dropped)
/// to prevent SSRF via env-var injection.
fn parse_relay_urls(raw: &str) -> Vec<String> {
    raw.split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .filter(|s| {
            if s.starts_with("ws://") || s.starts_with("wss://") {
                true
            } else {
                warn!(
                    "[ServerIdentity] Dropping invalid relay URL (must be ws:// or wss://): {}",
                    s
                );
                false
            }
        })
        .collect()
}

// ── tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// A deterministic hex secret key for reproducible tests. 32 bytes of 0x42.
    const TEST_HEX: &str =
        "4242424242424242424242424242424242424242424242424242424242424242";

    #[test]
    fn parse_secret_key_accepts_hex() {
        let sk = parse_secret_key(TEST_HEX).expect("hex parse");
        assert_eq!(sk.to_secret_hex(), TEST_HEX);
    }

    #[test]
    fn parse_secret_key_accepts_nsec() {
        let hex_sk = SecretKey::from_hex(TEST_HEX).unwrap();
        let nsec = hex_sk.to_bech32().unwrap();
        let parsed = parse_secret_key(&nsec).expect("nsec parse");
        assert_eq!(parsed.to_secret_hex(), TEST_HEX);
    }

    #[test]
    fn parse_secret_key_rejects_rubbish() {
        assert!(parse_secret_key("not a key").is_err());
        assert!(parse_secret_key("").is_err());
        assert!(parse_secret_key("npub1...").is_err()); // wrong bech32 prefix
    }

    #[test]
    fn parse_relay_urls_filters_bad_schemes() {
        let out = parse_relay_urls("wss://relay.damus.io, http://evil.com , , ws://localhost:7777");
        assert_eq!(
            out,
            vec![
                "wss://relay.damus.io".to_string(),
                "ws://localhost:7777".to_string(),
            ]
        );
    }

    #[test]
    fn parse_relay_urls_empty_input_yields_empty_vec() {
        assert!(parse_relay_urls("").is_empty());
        assert!(parse_relay_urls("   ").is_empty());
        assert!(parse_relay_urls(",,,").is_empty());
    }

    #[tokio::test]
    async fn sign_event_produces_verifiable_signature() {
        let sk = SecretKey::from_hex(TEST_HEX).unwrap();
        let identity = ServerIdentity {
            keys: Keys::new(sk),
            relay_urls: vec![],
            client: None,
        };
        let tags = vec![Tag::custom(
            TagKind::Custom("d".into()),
            vec!["test-id".to_string()],
        )];
        let event = identity
            .sign_event(30023, r#"{"hello":"world"}"#.to_string(), tags)
            .await
            .expect("sign");

        event.verify().expect("signature must verify");
        assert_eq!(event.kind.as_u16(), 30023);
        assert_eq!(event.pubkey.to_hex(), identity.pubkey_hex());
    }

    #[tokio::test]
    async fn sign_and_broadcast_without_client_still_returns_event() {
        let sk = SecretKey::from_hex(TEST_HEX).unwrap();
        let identity = ServerIdentity {
            keys: Keys::new(sk),
            relay_urls: vec![],
            client: None,
        };
        let event = identity
            .sign_and_broadcast(30300, r#"{"action":"test"}"#.to_string(), vec![])
            .await
            .expect("sign_and_broadcast must succeed without relays");
        event.verify().unwrap();
    }

    #[test]
    fn pubkey_hex_and_npub_are_equivalent() {
        let sk = SecretKey::from_hex(TEST_HEX).unwrap();
        let identity = ServerIdentity {
            keys: Keys::new(sk),
            relay_urls: vec![],
            client: None,
        };
        let hex = identity.pubkey_hex();
        let npub = identity.pubkey_npub();
        assert_eq!(hex.len(), 64);
        assert!(npub.starts_with("npub1"));
        // Round-trip
        let pk_from_npub = PublicKey::from_bech32(&npub).unwrap();
        assert_eq!(pk_from_npub.to_hex(), hex);
    }
}
