#!/usr/bin/env bash
# Godot Headless Operations for game-dev skill
# Provides: project validation, GDScript linting, scene testing, export

set -euo pipefail

GODOT_BIN="${GODOT_BIN:-godot}"
DISPLAY="${DISPLAY:-:1}"

usage() {
    cat <<'EOF'
Usage: godot-headless.sh <command> [options]

Commands:
  validate <project-path>     Validate Godot project structure
  lint <script-path>          Check GDScript file for errors
  run-scene <scene-path>      Run a scene headlessly (with timeout)
  run-tests <project-path>    Run GUT/GdUnit tests if present
  export <project-path> <preset>  Export project with named preset
  info                        Show Godot version and capabilities
  create-project <path> <name>  Create minimal Godot project
EOF
}

cmd_validate() {
    local project_path="$1"
    if [[ ! -f "${project_path}/project.godot" ]]; then
        echo "ERROR: No project.godot found at ${project_path}"
        return 1
    fi
    echo "Validating Godot project at ${project_path}..."
    # Open and immediately quit to check for parse errors
    # "no main scene" is expected for new projects - not a validation failure
    local output
    output=$(DISPLAY=$DISPLAY $GODOT_BIN --headless --path "$project_path" --quit 2>&1) || true
    echo "$output" | grep -v "no main scene defined" || true
    if echo "$output" | grep -qi "error.*parse\|error.*load\|fatal"; then
        echo "VALIDATION FAILED: Project has parse or load errors."
        return 1
    fi
    echo "Project validation complete."
}

cmd_lint() {
    local script_path="$1"
    if [[ ! -f "$script_path" ]]; then
        echo "ERROR: Script not found: ${script_path}"
        return 1
    fi
    echo "Linting GDScript: ${script_path}"
    # Use Godot's built-in script checking
    local project_dir
    project_dir=$(dirname "$script_path")
    while [[ "$project_dir" != "/" ]] && [[ ! -f "${project_dir}/project.godot" ]]; do
        project_dir=$(dirname "$project_dir")
    done
    if [[ -f "${project_dir}/project.godot" ]]; then
        DISPLAY=$DISPLAY $GODOT_BIN --headless --path "$project_dir" --check-only --script "$script_path" 2>&1
    else
        echo "WARNING: No project.godot found in parent directories. Limited checking available."
        # Basic syntax check without project context
        python3 -c "
import re, sys
with open('$script_path') as f:
    lines = f.readlines()
errors = []
for i, line in enumerate(lines, 1):
    stripped = line.rstrip()
    if stripped and not stripped.startswith('#') and not stripped.startswith('@'):
        # Check basic indentation (tabs only in GDScript)
        if stripped != line.lstrip() and not line.startswith('\t') and not line.startswith(' '):
            errors.append(f'Line {i}: Mixed indentation')
for e in errors:
    print(e)
if not errors:
    print('No basic syntax issues found.')
" 2>&1
    fi
}

cmd_run_scene() {
    local scene_path="$1"
    local timeout="${2:-10}"
    echo "Running scene headlessly: ${scene_path} (timeout: ${timeout}s)"
    local project_dir
    project_dir=$(dirname "$scene_path")
    while [[ "$project_dir" != "/" ]] && [[ ! -f "${project_dir}/project.godot" ]]; do
        project_dir=$(dirname "$project_dir")
    done
    timeout "$timeout" $GODOT_BIN --headless --path "$project_dir" "$scene_path" 2>&1 || true
}

cmd_run_tests() {
    local project_path="$1"
    echo "Looking for test frameworks in ${project_path}..."
    if [[ -d "${project_path}/addons/gut" ]]; then
        echo "Found GUT (Godot Unit Test). Running tests..."
        DISPLAY=$DISPLAY timeout 60 $GODOT_BIN --headless --path "$project_path" \
            -s "res://addons/gut/gut_cmdln.gd" 2>&1 || true
    elif [[ -d "${project_path}/addons/gdUnit4" ]]; then
        echo "Found gdUnit4. Running tests..."
        DISPLAY=$DISPLAY timeout 60 $GODOT_BIN --headless --path "$project_path" \
            -s "res://addons/gdUnit4/bin/GdUnitCmdTool.gd" --headless 2>&1 || true
    else
        echo "No test framework detected (GUT or gdUnit4)."
        echo "Install GUT: https://github.com/bitwes/Gut"
        echo "Install gdUnit4: https://github.com/MikeSchulze/gdUnit4"
    fi
}

cmd_export() {
    local project_path="$1"
    local preset="$2"
    echo "Exporting project with preset: ${preset}"
    DISPLAY=$DISPLAY $GODOT_BIN --headless --path "$project_path" --export-release "$preset" 2>&1
}

cmd_info() {
    echo "=== Godot Engine Info ==="
    $GODOT_BIN --version 2>&1
    echo "Binary: $(which $GODOT_BIN)"
    echo "Display: ${DISPLAY}"
    echo "Headless support: yes"
}

cmd_create_project() {
    local path="$1"
    local name="${2:-NewProject}"
    mkdir -p "$path"
    cat > "${path}/project.godot" << PROJ
; Engine configuration file.
; Generated by game-dev skill.

config_version=5

[application]
config/name="${name}"
config/features=PackedStringArray("4.6")

[rendering]
renderer/rendering_method="forward_plus"
PROJ
    echo "Created Godot project at ${path}"
}

case "${1:-}" in
    validate)       cmd_validate "${2:?Project path required}" ;;
    lint)           cmd_lint "${2:?Script path required}" ;;
    run-scene)      cmd_run_scene "${2:?Scene path required}" "${3:-10}" ;;
    run-tests)      cmd_run_tests "${2:?Project path required}" ;;
    export)         cmd_export "${2:?Project path required}" "${3:?Preset name required}" ;;
    info)           cmd_info ;;
    create-project) cmd_create_project "${2:?Path required}" "${3:-NewProject}" ;;
    *)              usage; exit 1 ;;
esac
