// ruvector-catalog — Technology recommender for the RuVector monorepo
// https://github.com/ruvnet/ruvector

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

const CATALOG_UPDATE_WORKFLOW = `# Auto-generated by ruvector-catalog v3.0
# Rebuilds the catalog when ruvector source changes
name: Update Catalog

on:
  push:
    branches: [main]
    paths:
      - 'crates/**'
      - 'examples/**'
      - 'docs/adr/**'
      - 'npm/packages/**'

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd ruvector-catalog-v3 && bun install

      - name: Build catalog
        run: cd ruvector-catalog-v3 && bun scripts/build-catalog.ts

      - name: Verify catalog completeness
        run: cd ruvector-catalog-v3 && bun src/cli.ts verify-completeness

      - name: Commit updated catalog
        run: |
          git config user.name "ruvector-catalog[bot]"
          git config user.email "catalog@ruvector.dev"
          git add ruvector-catalog-v3/catalog.store.json
          if git diff --cached --quiet; then
            echo "No catalog changes"
          else
            git commit -m "chore(catalog): auto-rebuild from source changes"
            git push
          fi
`;

const CATALOG_VERIFY_WORKFLOW = `# Auto-generated by ruvector-catalog v3.0
# Verifies catalog completeness on PRs that touch crates
name: Verify Catalog

on:
  pull_request:
    paths:
      - 'crates/**'
      - 'examples/**'

jobs:
  verify-catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd ruvector-catalog-v3 && bun install

      - name: Check for undocumented crates
        run: cd ruvector-catalog-v3 && bun src/cli.ts verify-completeness --strict
        continue-on-error: true

      - name: Post review comment
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'RuVector Catalog: New crates detected that are not in the catalog. Run bun ruvector-catalog-v3/src/cli.ts build to update.'
            })
`;

export class WorkflowGenerator {
  private projectRoot: string;

  constructor(projectRoot?: string) {
    this.projectRoot = projectRoot ?? process.cwd();
  }

  generate(): string[] {
    const workflowDir = join(this.projectRoot, '.github', 'workflows');
    if (!existsSync(workflowDir)) {
      mkdirSync(workflowDir, { recursive: true });
    }

    const files: string[] = [];

    const updatePath = join(workflowDir, 'catalog-update.yml');
    writeFileSync(updatePath, CATALOG_UPDATE_WORKFLOW, 'utf-8');
    files.push(updatePath);

    const verifyPath = join(workflowDir, 'catalog-verify.yml');
    writeFileSync(verifyPath, CATALOG_VERIFY_WORKFLOW, 'utf-8');
    files.push(verifyPath);

    return files;
  }
}
