// @visionflow/contracts — index re-export.
//
// Source of truth lives in `crates/visionclaw-contracts/src/` (Rust). The
// `bindings/` directory is regenerated by:
//
//   cargo test -p visionclaw-contracts --features typescript-export ts_export
//
// Both VisionFlow itself (Rust) and JavaScript consumers (agentbox, forum,
// the React XR control panel) depend on this package. The schema version is
// embedded in the package version (`0.1.0-v1`) — bumps require a coordinated
// deploy per ADR-10 §D8.

// AgentAction (ADR-10 §D3 / T7 resolution)
export type { AgentActionEnvelope } from "./bindings/AgentActionEnvelope";
export type { AgentAction } from "./bindings/AgentAction";
export type { ActionKind } from "./bindings/ActionKind";
export type { NodeClass } from "./bindings/NodeClass";
export type { ModifierKeys } from "./bindings/ModifierKeys";
export type { WorldPosition } from "./bindings/WorldPosition";

// Agent telemetry (ADR-10 §D1)
export type { AgentTelemetryEnvelope } from "./bindings/AgentTelemetryEnvelope";
export type { AgentTelemetryEvent } from "./bindings/AgentTelemetryEvent";
export type { SnapshotPayload } from "./bindings/SnapshotPayload";
export type { DeltaPayload } from "./bindings/DeltaPayload";
export type { AgentRemovedPayload } from "./bindings/AgentRemovedPayload";
export type { HeartbeatPayload } from "./bindings/HeartbeatPayload";
export type { CommunicationPayload } from "./bindings/CommunicationPayload";
export type { AgentRecord } from "./bindings/AgentRecord";
export type { AgentStatus } from "./bindings/AgentStatus";

// Enterprise events (ADR-10 §D5)
export type { EnterpriseEventEnvelope } from "./bindings/EnterpriseEventEnvelope";
export type { EnterpriseEventKind } from "./bindings/EnterpriseEventKind";
export type { MembershipChangePayload } from "./bindings/MembershipChangePayload";
export type { MembershipAction } from "./bindings/MembershipAction";
export type { RoleChangePayload } from "./bindings/RoleChangePayload";
export type { EnterpriseRole } from "./bindings/EnterpriseRole";
export type { SessionRevokedPayload } from "./bindings/SessionRevokedPayload";

// GitHub adapter boundary value object (ADR-10 §D11)
export type { ParsedMarkdown } from "./bindings/ParsedMarkdown";
export type { ParseErrorReport } from "./bindings/ParseErrorReport";
export type { ParseErrorKind } from "./bindings/ParseErrorKind";

// Runtime constants (mirrored from Rust — see ./index.js).
export const AGENT_ACTION_CHANNEL: "visionflow:agent-actions";
export const AGENT_ACTION_TYPE: "visionflow:agent-action";
export const SCHEMA_VERSION: 1;
export const SCHEMA_VERSION_STRING: "v1";
