// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminated action kind. Forward-compatible — receivers MUST treat
 * any unknown value as a no-op (ADR-10 §D3).
 */
export type ActionKind = "open_panel" | "show_logs" | "show_swarm" | "show_lineage";
