// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse agent status. Renderer maps these to colour / opacity (PRD-07 F4).
 * Wire encoding is `snake_case`.
 */
export type AgentStatus = "spawning" | "running" | "idle" | "stopped" | "errored";
