// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";

/**
 * One row from a `snapshot` or one `agent_added` body. Internal events
 * (`AgentJoined`, `SwarmSnapshot`) project this into the DDD-07 aggregate.
 */
export type AgentRecord = { agent_id: string, 
/**
 * Free-form agent kind label (`researcher`, `coder`, `tester`, …).
 * Open-ended by design — the agentbox owns the taxonomy.
 */
kind: string, status: AgentStatus, swarm_id: string | null, spawned_at_ms: bigint, last_activity_ms: bigint | null, 
/**
 * Opaque agentbox metadata, passed through unmodified.
 */
metadata: Record<string, unknown> | null, };
