// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRecord } from "./AgentRecord";
import type { AgentRemovedPayload } from "./AgentRemovedPayload";
import type { CommunicationPayload } from "./CommunicationPayload";
import type { DeltaPayload } from "./DeltaPayload";
import type { HeartbeatPayload } from "./HeartbeatPayload";
import type { SnapshotPayload } from "./SnapshotPayload";

/**
 * Discriminated wire event. The `tag = "type"` and `content = "payload"`
 * adjacent shape matches ADR-10 §D1's JSON literally:
 * `{"type": "snapshot", "payload": { ... }}`.
 */
export type AgentTelemetryEvent = { "type": "snapshot", "payload": SnapshotPayload } | { "type": "delta", "payload": DeltaPayload } | { "type": "agent_added", "payload": AgentRecord } | { "type": "agent_removed", "payload": AgentRemovedPayload } | { "type": "heartbeat", "payload": HeartbeatPayload } | { "type": "communication", "payload": CommunicationPayload };
