// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAction } from "./AgentAction";

/**
 * Top-level envelope dispatched on every agent-node interaction.
 *
 * Serde serialises this as a discriminated union with `"type":
 * "visionclaw:agent-action"` at the top level. The enum has a single variant
 * today; future incompatible shapes would be introduced by bumping
 * `schema_version` rather than by adding a sibling variant.
 */
export type AgentActionEnvelope = { "type": "visionclaw:agent-action" } & AgentAction;
