// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeltaPayload = { agent_id: string, 
/**
 * Field set varies — opaque on the wire and parsed by the consumer.
 * Modelled as `serde_json::Value` because the field-level schema is
 * open-ended by design (ADR-10 §D1: "the next snapshot corrects it").
 */
fields: Record<string, unknown>, };
