// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MembershipChangePayload } from "./MembershipChangePayload";
import type { RoleChangePayload } from "./RoleChangePayload";
import type { SessionRevokedPayload } from "./SessionRevokedPayload";

/**
 * Top-level enterprise event envelope.
 */
export type EnterpriseEventEnvelope = { schema_version: number, issued_at_ms: bigint, } & ({ "type": "membership_change", "payload": MembershipChangePayload } | { "type": "role_change", "payload": RoleChangePayload } | { "type": "session_revoked", "payload": SessionRevokedPayload });
