// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParseErrorKind } from "./ParseErrorKind";

/**
 * One parse failure surfaced by the GitHub adapter.
 *
 * Errors are logged but do not fail the sync; the failed file is retained
 * at its previous good version. The shape matches ADR-10 §D11 verbatim.
 */
export type ParseErrorReport = { path: string, sha: string, error_kind: ParseErrorKind, message: string, };
