// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminated parse-error category. Drives the metric label
 * `github_sync_parse_errors_total{error_kind}`.
 */
export type ParseErrorKind = "yaml" | "wikilink" | "ontology-block" | "io";
