// ruvector-catalog — Technology recommender for the RuVector monorepo
// https://github.com/ruvnet/ruvector
// Capabilities 4-16: V3 fields with defaults (to be enriched in later passes)

import type { Capability } from '../types/index.js';

export const DEFAULT_CAPABILITIES: Capability[] = [
  {
    id: 'self_learning',
    description: 'Systems that improve from experience',
    primaryCrate: 'sona',
    status: 'production',
    docPath: 'docs/self_learning.md',
    keywords: ['learn', 'adapt', 'improve', 'lora', 'fine-tune', 'training', 'reinforcement', 'ewc', 'sona', 'reasoning', 'experience', 'memory'],
    problemStatement: 'I need a system that learns and adapts from experience',
    synonyms: ['self-improving AI', 'continual learning', 'fine-tuning', 'adaptation'],
    relatedCapabilities: ['llm_runtime', 'agents', 'attention_mechanisms'],
    technologies: [
      { id: 'sona', name: 'SONA', crate: 'sona', capabilityId: 'self_learning', complexity: null, latency: '<1ms adapt', status: 'production', useWhen: 'adaptive learning with 3 loops (instant MicroLoRA, background LoRA, deep EWC++)', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/sona', algorithms: [{ name: 'MicroLoRA', technologyId: 'sona', crate: 'sona', complexity: null, description: 'Per-request adaptation <1MB, rank-2' }, { name: 'EWC++', technologyId: 'sona', crate: 'sona', complexity: null, description: 'Elastic Weight Consolidation for continual learning' }], useCases: [], problemDomains: [], verticals: [], plainDescription: 'A self-learning engine that adapts to new data in milliseconds without forgetting what it already knows.', relatedExamples: ['OSpipe'], primaryFor: ['self-learning', 'continual-learning'] },
      { id: 'reasoning-bank', name: 'ReasoningBank', crate: 'sona', capabilityId: 'self_learning', complexity: null, latency: null, status: 'production', useWhen: 'learning from LLM trajectories with HNSW-indexed pattern search', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/sona', algorithms: [], useCases: [], problemDomains: [], verticals: [], plainDescription: 'A memory bank that stores and retrieves reasoning patterns so AI agents learn from past decisions.', relatedExamples: [], primaryFor: [] },
      { id: 'micro-lora-wasm', name: 'MicroLoRA (WASM)', crate: 'ruvector-learning-wasm', capabilityId: 'self_learning', complexity: null, latency: '<100us', status: 'production', useWhen: 'edge/browser adaptation with rank-2 LoRA', features: null, deploymentTargets: ['wasm'], sourcePath: 'crates/ruvector-learning-wasm', algorithms: [], useCases: [], problemDomains: [], verticals: ['edge-iot'], plainDescription: 'Adapts models right in the browser or on edge devices in microseconds.', relatedExamples: [], primaryFor: [] },
      { id: 'domain-expansion', name: 'Domain Expansion', crate: 'ruvector-domain-expansion', capabilityId: 'self_learning', complexity: null, latency: null, status: 'experimental', useWhen: 'cross-domain transfer learning, meta Thompson sampling', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvector-domain-expansion', algorithms: [], useCases: [], problemDomains: [], verticals: [], plainDescription: 'Transfers learning from one domain to another, so a model trained on finance can help with healthcare.', relatedExamples: [], primaryFor: [] },
    ],
  },
  {
    id: 'coherence_safety',
    description: 'AI safety, hallucination detection, governance',
    primaryCrate: 'prime-radiant',
    status: 'production',
    docPath: 'docs/coherence_safety.md',
    keywords: ['hallucination', 'drift', 'coherence', 'safety', 'verify', 'governance', 'trust', 'proof', 'witness', 'pii', 'compliance'],
    problemStatement: 'I need to verify AI outputs / prevent hallucination / detect drift',
    synonyms: ['catch contradictions', 'ensure consistency', 'fact-check AI', 'validate reasoning', 'AI governance'],
    relatedCapabilities: ['graph_intelligence', 'attention_mechanisms'],
    technologies: [
      { id: 'prime-radiant', name: 'Prime Radiant', crate: 'prime-radiant', capabilityId: 'coherence_safety', complexity: null, latency: null, status: 'production', useWhen: 'universal coherence engine with sheaf cohomology and governance', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/prime-radiant', algorithms: [{ name: 'Sheaf Laplacian', technologyId: 'prime-radiant', crate: 'prime-radiant', complexity: null, description: 'H^0 global sections, H^1 obstructions for consistency' }], useCases: [], problemDomains: ['coherence', 'safety', 'hallucination-detection'], verticals: ['healthcare', 'finance'], plainDescription: 'A fact-checking engine for AI -- catches contradictions and flags when an AI is making things up.', relatedExamples: ['prime-radiant', 'verified-applications'], primaryFor: ['hallucination-detection', 'coherence-verification'] },
      { id: 'coherence-gate', name: '256-Tile Coherence Gate', crate: 'cognitum-gate-kernel', capabilityId: 'coherence_safety', complexity: null, latency: null, status: 'production', useWhen: '64KB per-tile WASM kernel for evidence accumulation', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/cognitum-gate-kernel', algorithms: [], useCases: [], problemDomains: ['coherence', 'evidence'], verticals: [], plainDescription: 'A WASM-based gate that accumulates evidence before letting AI outputs through.', relatedExamples: [], primaryFor: [] },
      { id: 'tilezero', name: 'TileZero Arbiter', crate: 'cognitum-gate-tilezero', capabilityId: 'coherence_safety', complexity: null, latency: null, status: 'production', useWhen: 'central arbiter with supergraph merging and permit tokens', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/cognitum-gate-tilezero', algorithms: [], useCases: [], problemDomains: ['governance', 'arbiter'], verticals: [], plainDescription: 'A central judge that merges evidence from multiple coherence tiles and issues permits.', relatedExamples: [], primaryFor: [] },
      { id: 'verified', name: 'Formal Verification', crate: 'ruvector-verified', capabilityId: 'coherence_safety', complexity: null, latency: null, status: 'production', useWhen: 'SAT/SMT solver, bounded model checking, K-induction proofs', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvector-verified', algorithms: [], useCases: [], problemDomains: ['formal-verification', 'proof'], verticals: [], plainDescription: 'Mathematically proves that AI systems behave correctly, like a theorem prover for software.', relatedExamples: ['verified-applications'], primaryFor: [] },
      { id: 'cusum-drift', name: 'CUSUM Drift Detection', crate: 'neural-trader-coherence', capabilityId: 'coherence_safety', complexity: null, latency: null, status: 'production', useWhen: 'detecting distribution drift in model outputs', features: null, deploymentTargets: ['native'], sourcePath: 'crates/neural-trader-coherence', algorithms: [{ name: 'CUSUM', technologyId: 'cusum-drift', crate: 'neural-trader-coherence', complexity: null, description: 'Cumulative sum control chart for drift detection' }], useCases: [], problemDomains: ['drift-detection', 'monitoring'], verticals: ['finance'], plainDescription: 'Detects when an AI model starts behaving differently from how it was trained.', relatedExamples: ['neural-trader'], primaryFor: [] },
    ],
  },
  {
    id: 'nervous_system',
    description: '5-layer bio-inspired neural architecture',
    primaryCrate: 'ruvector-nervous-system',
    status: 'production',
    docPath: 'docs/nervous_system.md',
    keywords: ['bio', 'neuron', 'spiking', 'brain', 'hopfield', 'hdc', 'hyperdimensional', 'dendritic', 'oscillator', 'predictive coding'],
    problemStatement: 'I need bio-inspired computing / neuromorphic processing / brain-like AI',
    synonyms: ['spiking neurons', 'brain-inspired', 'neuromorphic', 'associative memory'],
    relatedCapabilities: ['attention_mechanisms', 'self_learning'],
    technologies: [
      { id: 'spiking-nn', name: 'Spiking Neural Networks', crate: 'ruvector-nervous-system', capabilityId: 'nervous_system', complexity: null, latency: null, status: 'production', useWhen: 'event-driven neural processing with LIF neurons + STDP', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvector-nervous-system', algorithms: [{ name: 'STDP', technologyId: 'spiking-nn', crate: 'ruvector-nervous-system', complexity: null, description: 'Spike-Timing-Dependent Plasticity' }], useCases: [], problemDomains: ['neuromorphic', 'spiking'], verticals: ['robotics', 'edge-iot'], plainDescription: 'Brain-like neurons that fire only when needed, ideal for low-power robotics and edge AI.', relatedExamples: ['spiking-network'], primaryFor: ['neuromorphic'] },
      { id: 'hdc', name: 'Hyperdimensional Computing', crate: 'ruvector-nervous-system', capabilityId: 'nervous_system', complexity: null, latency: '<100ns', status: 'production', useWhen: '10,000-bit binary hypervectors for ultra-fast classification', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvector-nervous-system', algorithms: [], useCases: [], problemDomains: ['classification', 'hyperdimensional'], verticals: ['edge-iot'], plainDescription: 'Ultra-fast classification using 10,000-bit vectors, runs in nanoseconds.', relatedExamples: [], primaryFor: [] },
      { id: 'hopfield', name: 'Modern Hopfield Networks', crate: 'ruvector-nervous-system', capabilityId: 'nervous_system', complexity: null, latency: null, status: 'production', useWhen: 'associative memory with exponential storage 2^(d/2)', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvector-nervous-system', algorithms: [], useCases: [], problemDomains: ['associative-memory'], verticals: [], plainDescription: 'A memory network that retrieves complete patterns from partial cues.', relatedExamples: [], primaryFor: [] },
      { id: 'predictive-coding', name: 'Predictive Coding', crate: 'ruvector-nervous-system', capabilityId: 'nervous_system', complexity: null, latency: null, status: 'production', useWhen: '90-99% bandwidth reduction via prediction error signals', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvector-nervous-system', algorithms: [], useCases: [], problemDomains: ['bandwidth-reduction', 'predictive'], verticals: ['edge-iot'], plainDescription: 'Reduces data transfer by 90-99% by only sending what was unexpected.', relatedExamples: [], primaryFor: [] },
      { id: 'global-workspace', name: 'Global Workspace', crate: 'ruvector-nervous-system', capabilityId: 'nervous_system', complexity: null, latency: null, status: 'production', useWhen: 'consciousness-inspired 4-7 item broadcast capacity', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvector-nervous-system', algorithms: [], useCases: [], problemDomains: ['cognitive-architecture'], verticals: [], plainDescription: 'A consciousness-inspired architecture that broadcasts important information to all modules.', relatedExamples: [], primaryFor: [] },
    ],
  },
  {
    id: 'mathematics',
    description: 'Advanced mathematics for vector and graph operations',
    primaryCrate: 'ruvector-math',
    status: 'production',
    docPath: 'docs/mathematics.md',
    keywords: ['math', 'optimal transport', 'wasserstein', 'topology', 'tensor', 'geometry', 'spectral', 'fisher', 'tropical', 'homology'],
    problemStatement: 'I need advanced math primitives / optimal transport / topological analysis',
    synonyms: ['distribution comparison', 'tensor decomposition', 'natural gradient', 'TDA'],
    relatedCapabilities: ['vector_search', 'solvers'],
    technologies: [
      { id: 'optimal-transport', name: 'Optimal Transport', crate: 'ruvector-math', capabilityId: 'mathematics', complexity: null, latency: null, status: 'production', useWhen: 'Wasserstein distance, Sinkhorn, Gromov-Wasserstein for distribution comparison', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvector-math', algorithms: [{ name: 'Sinkhorn', technologyId: 'optimal-transport', crate: 'ruvector-math', complexity: null, description: 'Log-stabilized optimal transport solver' }], useCases: [], problemDomains: ['distribution-comparison'], verticals: [], plainDescription: 'Measures how different two distributions are, like comparing populations or datasets.', relatedExamples: [], primaryFor: [] },
      { id: 'tropical-geometry', name: 'Tropical Geometry', crate: 'ruvector-math', capabilityId: 'mathematics', complexity: null, latency: null, status: 'production', useWhen: 'max-plus semiring, neural network linear region counting', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvector-math', algorithms: [], useCases: [], problemDomains: ['neural-geometry'], verticals: [], plainDescription: 'Mathematical tools that count the decision boundaries inside neural networks.', relatedExamples: [], primaryFor: [] },
      { id: 'persistent-homology', name: 'Persistent Homology (TDA)', crate: 'ruvector-math', capabilityId: 'mathematics', complexity: null, latency: null, status: 'production', useWhen: 'topological data analysis, Betti numbers, persistence diagrams', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvector-math', algorithms: [], useCases: [], problemDomains: ['topological-data-analysis'], verticals: ['genomics'], plainDescription: 'Finds the shape of data -- holes, loops, and clusters that survive across scales.', relatedExamples: [], primaryFor: [] },
      { id: 'tensor-networks', name: 'Tensor Networks', crate: 'ruvector-math', capabilityId: 'mathematics', complexity: null, latency: null, status: 'production', useWhen: 'tensor train, Tucker, CP decomposition for dimensionality reduction', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvector-math', algorithms: [], useCases: [], problemDomains: ['dimensionality-reduction'], verticals: [], plainDescription: 'Compresses high-dimensional data into efficient tensor formats.', relatedExamples: [], primaryFor: [] },
      { id: 'info-geometry', name: 'Information Geometry', crate: 'ruvector-math', capabilityId: 'mathematics', complexity: null, latency: null, status: 'production', useWhen: 'Fisher metric, K-FAC, natural gradient (3-5x fewer iterations than Adam)', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvector-math', algorithms: [{ name: 'Natural Gradient', technologyId: 'info-geometry', crate: 'ruvector-math', complexity: null, description: 'Fisher Information Matrix approximated via K-FAC' }], useCases: [], problemDomains: ['optimization'], verticals: [], plainDescription: 'Trains neural networks 3-5x faster using the geometry of probability distributions.', relatedExamples: [], primaryFor: [] },
    ],
  },
  {
    id: 'solvers',
    description: '8 algorithms for sparse linear systems and PageRank',
    primaryCrate: 'ruvector-solver',
    status: 'production',
    docPath: 'docs/solvers.md',
    keywords: ['solver', 'linear system', 'sparse', 'pagerank', 'conjugate gradient', 'neumann', 'multigrid', 'laplacian'],
    problemStatement: 'I need to solve large sparse linear systems / compute PageRank',
    synonyms: ['matrix solver', 'sparse computation', 'linear algebra'],
    relatedCapabilities: ['mathematics', 'graph_intelligence'],
    technologies: [
      { id: 'auto-solver', name: 'Auto-Router Solver', crate: 'ruvector-solver', capabilityId: 'solvers', complexity: 'varies', latency: null, status: 'production', useWhen: "don't know which solver -- auto-selects best algorithm", features: null, deploymentTargets: ['native', 'wasm', 'nodejs'], sourcePath: 'crates/ruvector-solver', algorithms: [{ name: 'Neumann Series', technologyId: 'auto-solver', crate: 'ruvector-solver', complexity: 'O(nnz*log n)', description: 'For diagonally-dominant systems' }, { name: 'Conjugate Gradient', technologyId: 'auto-solver', crate: 'ruvector-solver', complexity: 'O(sqrt(kappa)*nnz)', description: 'For SPD systems' }, { name: 'TRUE Solver', technologyId: 'auto-solver', crate: 'ruvector-solver', complexity: 'O(log n)', description: 'Sublinear batch solver' }], useCases: [], problemDomains: ['linear-systems'], verticals: [], plainDescription: 'Automatically picks the best algorithm to solve your math problem, like a GPS for linear algebra.', relatedExamples: [], primaryFor: ['sparse-solvers'] },
    ],
  },
  {
    id: 'mincut',
    description: 'Dynamic minimum cut -- largest crate at 45,911 LOC',
    primaryCrate: 'ruvector-mincut',
    status: 'production',
    docPath: 'docs/mincut.md',
    keywords: ['mincut', 'min-cut', 'graph partitioning', 'flow', 'max-flow', 'gomory-hu', 'expander', 'sparsification'],
    problemStatement: 'I need graph partitioning / network flow / min-cut computation',
    synonyms: ['split a graph', 'divide networks', 'bottleneck detection'],
    relatedCapabilities: ['graph_intelligence', 'attention_mechanisms'],
    technologies: [
      { id: 'dynamic-mincut', name: 'Dynamic Min-Cut', crate: 'ruvector-mincut', capabilityId: 'mincut', complexity: 'O(n^0.12) amortized', latency: null, status: 'production', useWhen: 'deterministic exact dynamic graph partitioning, 256-core parallel', features: null, deploymentTargets: ['native', 'wasm', 'nodejs'], sourcePath: 'crates/ruvector-mincut', algorithms: [{ name: "Karger's min-cut", technologyId: 'dynamic-mincut', crate: 'ruvector-mincut', complexity: null, description: 'Randomized min-cut' }, { name: 'Stoer-Wagner', technologyId: 'dynamic-mincut', crate: 'ruvector-mincut', complexity: null, description: 'Deterministic min-cut' }, { name: 'Gomory-Hu trees', technologyId: 'dynamic-mincut', crate: 'ruvector-mincut', complexity: null, description: 'All-pairs min-cut tree' }], useCases: [], problemDomains: ['graph-partitioning'], verticals: [], plainDescription: 'Finds the cheapest way to split a network into parts, used for load balancing and clustering.', relatedExamples: [], primaryFor: ['graph-partitioning'] },
    ],
  },
  {
    id: 'llm_runtime',
    description: 'Local LLM inference with learning',
    primaryCrate: 'ruvllm',
    status: 'production',
    docPath: 'docs/llm_runtime.md',
    keywords: ['llm', 'inference', 'model', 'quantization', 'bitnet', 'metal', 'gpu', 'cuda', 'webgpu', 'kv cache', 'batching', 'gguf'],
    problemStatement: 'I need local LLM inference / model serving / on-device AI',
    synonyms: ['run models locally', 'self-hosted AI', 'GPU inference', 'edge AI'],
    relatedCapabilities: ['self_learning', 'attention_mechanisms', 'agents'],
    technologies: [
      { id: 'ruvllm', name: 'RuVLLM', crate: 'ruvllm', capabilityId: 'llm_runtime', complexity: null, latency: null, status: 'production', useWhen: 'local LLM inference with paged attention, KV cache, SONA learning', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvllm', algorithms: [{ name: 'BitNet b1.58', technologyId: 'ruvllm', crate: 'ruvllm', complexity: null, description: 'Ternary {-1,0,+1} quantization, multiplication-free' }], useCases: [], problemDomains: ['llm-inference'], verticals: [], plainDescription: 'Run large language models locally on your own hardware with self-learning capabilities.', relatedExamples: [], primaryFor: ['local-llm'] },
      { id: 'metal-gpu', name: 'Apple Metal GPU', crate: 'ruvllm', capabilityId: 'llm_runtime', complexity: null, latency: null, status: 'production', useWhen: 'Apple Silicon M-series acceleration', features: null, deploymentTargets: ['native'], sourcePath: 'crates/ruvllm', algorithms: [], useCases: [], problemDomains: ['gpu-acceleration'], verticals: [], plainDescription: 'Accelerates AI models on Mac using the Apple M-series GPU.', relatedExamples: [], primaryFor: [] },
      { id: 'continuous-batching', name: 'Continuous Batching', crate: 'ruvllm', capabilityId: 'llm_runtime', complexity: null, latency: null, status: 'production', useWhen: 'production LLM serving with prefill/decode scheduling', features: null, deploymentTargets: ['native'], sourcePath: 'crates/ruvllm', algorithms: [], useCases: [], problemDomains: ['serving'], verticals: [], plainDescription: 'Serves many LLM requests at once by scheduling them efficiently.', relatedExamples: [], primaryFor: [] },
      { id: 'self-reflection', name: 'Self-Reflection', crate: 'ruvllm', capabilityId: 'llm_runtime', complexity: null, latency: null, status: 'production', useWhen: 'ReflectiveAgent with IoE confidence, multi-perspective critique', features: null, deploymentTargets: ['native'], sourcePath: 'crates/ruvllm', algorithms: [], useCases: [], problemDomains: ['reasoning'], verticals: [], plainDescription: 'An AI agent that critiques its own answers from multiple perspectives before responding.', relatedExamples: [], primaryFor: [] },
    ],
  },
  {
    id: 'quantum',
    description: 'Quantum circuit simulation and algorithms',
    primaryCrate: 'ruqu-core',
    status: 'research',
    docPath: 'docs/quantum.md',
    keywords: ['quantum', 'qubit', 'circuit', 'simulation', 'vqe', 'qaoa', 'grover', 'surface code', 'error correction'],
    problemStatement: 'I need quantum computing simulation / quantum algorithms',
    synonyms: ['quantum circuits', 'qubit simulation', 'quantum optimization'],
    relatedCapabilities: ['mathematics'],
    technologies: [
      { id: 'ruqu', name: 'RuQu Quantum Simulator', crate: 'ruqu-core', capabilityId: 'quantum', complexity: null, latency: null, status: 'research', useWhen: 'quantum circuit simulation up to 25 qubits in browser', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruqu-core', algorithms: [{ name: "Grover's Search", technologyId: 'ruqu', crate: 'ruqu-core', complexity: 'O(sqrt(N))', description: 'Quadratic speedup for unstructured search' }, { name: 'QAOA', technologyId: 'ruqu', crate: 'ruqu-core', complexity: null, description: 'Quantum Approximate Optimization for MaxCut' }, { name: 'VQE', technologyId: 'ruqu', crate: 'ruqu-core', complexity: null, description: 'Variational Quantum Eigensolver for molecular chemistry' }], useCases: [], problemDomains: ['quantum-simulation'], verticals: [], plainDescription: 'Simulates quantum computers in your browser, up to 25 qubits.', relatedExamples: ['OSpipe'], primaryFor: [] },
      { id: 'exotic-quantum', name: 'Exotic Quantum Hybrids', crate: 'ruqu-exotic', capabilityId: 'quantum', complexity: null, latency: null, status: 'research', useWhen: 'quantum decay, interference search, reversible memory, syndrome diagnosis', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruqu-exotic', algorithms: [], useCases: [], problemDomains: ['quantum-hybrid'], verticals: [], plainDescription: 'Experimental quantum-classical hybrid algorithms for specialized problems.', relatedExamples: [], primaryFor: [] },
    ],
  },
  {
    id: 'distributed',
    description: 'Multi-node consensus and replication',
    primaryCrate: 'ruvector-raft',
    status: 'production',
    docPath: 'docs/distributed.md',
    keywords: ['distributed', 'consensus', 'raft', 'replication', 'cluster', 'sharding', 'crdt', 'gossip', 'vector clock', 'failover'],
    problemStatement: 'I need distributed consensus / replication / multi-node coordination',
    synonyms: ['cluster management', 'data replication', 'fault tolerance', 'distributed database'],
    relatedCapabilities: ['storage'],
    technologies: [
      { id: 'raft', name: 'Raft Consensus', crate: 'ruvector-raft', capabilityId: 'distributed', complexity: null, latency: null, status: 'production', useWhen: 'leader election, log replication, snapshots', features: null, deploymentTargets: ['native'], sourcePath: 'crates/ruvector-raft', algorithms: [], useCases: [], problemDomains: ['consensus'], verticals: [], plainDescription: 'Keeps multiple servers in agreement even when some fail.', relatedExamples: [], primaryFor: ['consensus'] },
      { id: 'auto-sharding', name: 'Auto-Sharding', crate: 'ruvector-cluster', capabilityId: 'distributed', complexity: null, latency: null, status: 'production', useWhen: 'consistent hashing with 150 virtual nodes', features: null, deploymentTargets: ['native'], sourcePath: 'crates/ruvector-cluster', algorithms: [], useCases: [], problemDomains: ['sharding'], verticals: [], plainDescription: 'Automatically spreads data across servers so no single machine is overloaded.', relatedExamples: [], primaryFor: [] },
      { id: 'delta-crdt', name: 'Delta CRDT', crate: 'ruvector-delta-consensus', capabilityId: 'distributed', complexity: null, latency: null, status: 'production', useWhen: 'CRDT merging with hybrid logical clocks, causal ordering', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/ruvector-delta-consensus', algorithms: [], useCases: [], problemDomains: ['crdt', 'eventual-consistency'], verticals: [], plainDescription: 'Lets multiple users edit the same data offline and automatically merges changes.', relatedExamples: [], primaryFor: [] },
    ],
  },
  {
    id: 'storage',
    description: 'PostgreSQL, RVF containers, embedded DB',
    primaryCrate: 'ruvector-postgres',
    status: 'production',
    docPath: 'docs/storage.md',
    keywords: ['database', 'postgres', 'sql', 'rvf', 'container', 'embedded', 'rvlite', 'redb', 'persistence', 'storage'],
    problemStatement: 'I need a database / persistent storage / data containers',
    synonyms: ['store data', 'SQL database', 'embedded database', 'mobile database'],
    relatedCapabilities: ['vector_search', 'distributed'],
    technologies: [
      { id: 'postgres-ext', name: 'PostgreSQL Extension', crate: 'ruvector-postgres', capabilityId: 'storage', complexity: null, latency: null, status: 'production', useWhen: '230+ SQL functions, pgvector drop-in, TDA, graph, SONA', features: null, deploymentTargets: ['postgresql'], sourcePath: 'crates/ruvector-postgres', algorithms: [], useCases: [], problemDomains: ['database', 'sql'], verticals: [], plainDescription: 'Adds vector search, graph queries, and AI learning directly into PostgreSQL.', relatedExamples: [], primaryFor: ['postgresql-vector'] },
      { id: 'rvlite', name: 'RVLite', crate: 'rvlite', capabilityId: 'storage', complexity: null, latency: null, status: 'production', useWhen: 'embedded vector DB with SQL + SPARQL + Cypher (WASM, IndexedDB)', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/rvlite', algorithms: [], useCases: [], problemDomains: ['embedded-database', 'mobile'], verticals: [], plainDescription: 'A tiny database that runs in your browser or mobile app with vector search built in.', relatedExamples: [], primaryFor: [] },
      { id: 'rvf', name: 'RVF Cognitive Containers', crate: 'rvf', capabilityId: 'storage', complexity: null, latency: null, status: 'production', useWhen: '19 sub-crate container format with crypto, runtime, federation', features: null, deploymentTargets: ['native', 'wasm', 'nodejs'], sourcePath: 'crates/rvf', algorithms: [], useCases: [], problemDomains: ['containers', 'packaging'], verticals: [], plainDescription: 'Smart data containers that carry their own runtime, crypto, and federation logic.', relatedExamples: [], primaryFor: [] },
    ],
  },
  {
    id: 'agents',
    description: 'Agent framework with 9 sub-crates',
    primaryCrate: 'rvagent-core',
    status: 'production',
    docPath: 'docs/self_learning.md',
    keywords: ['agent', 'framework', 'middleware', 'mcp', 'tool', 'subagent', 'orchestration', 'acp', 'routing', 'coding agent'],
    problemStatement: 'I need an AI agent framework / tool orchestration / MCP integration',
    synonyms: ['build agents', 'agent routing', 'model orchestration', 'agentic AI'],
    relatedCapabilities: ['self_learning', 'llm_runtime'],
    technologies: [
      { id: 'rvagent', name: 'rvAgent Framework', crate: 'rvagent-core', capabilityId: 'agents', complexity: null, latency: null, status: 'production', useWhen: 'building AI agents with state machine, 19 middleware types, MCP bridge', features: null, deploymentTargets: ['native', 'wasm', 'nodejs'], sourcePath: 'crates/rvagent-core', algorithms: [], useCases: [], problemDomains: ['agent-framework'], verticals: [], plainDescription: 'A framework for building AI agents with tools, memory, and multi-step reasoning.', relatedExamples: [], primaryFor: ['agent-framework'] },
      { id: 'tiny-dancer', name: 'Tiny Dancer Router', crate: 'ruvector-tiny-dancer-core', capabilityId: 'agents', complexity: null, latency: null, status: 'production', useWhen: 'FastGRNN neural routing to pick optimal model per query', features: null, deploymentTargets: ['native', 'wasm', 'nodejs'], sourcePath: 'crates/ruvector-tiny-dancer-core', algorithms: [], useCases: [], problemDomains: ['model-routing'], verticals: [], plainDescription: 'A neural router that picks the best AI model for each question.', relatedExamples: [], primaryFor: [] },
      { id: 'mcp-brain', name: 'MCP Brain', crate: 'mcp-brain', capabilityId: 'agents', complexity: null, latency: null, status: 'production', useWhen: 'shared brain MCP server (Firestore + GCS), cross-session transfer learning', features: null, deploymentTargets: ['native'], sourcePath: 'crates/mcp-brain', algorithms: [], useCases: [], problemDomains: ['shared-memory', 'mcp'], verticals: [], plainDescription: 'A shared brain for AI agents that persists memory across sessions.', relatedExamples: [], primaryFor: [] },
      { id: 'ospipe', name: 'OSpipe (ScreenPipe)', crate: 'rvagent-core', capabilityId: 'agents', complexity: null, latency: null, status: 'production', useWhen: 'monitor all user actions on desktop, screen capture, suggest efficiency improvements through AI automation', features: 'ScreenPipe integration, semantic AI memory, desktop monitoring, user action tracking', deploymentTargets: ['native'], sourcePath: 'examples/OSpipe', algorithms: [], useCases: ['desktop monitoring', 'user action tracking', 'efficiency improvement', 'AI automation', 'screen capture'], problemDomains: ['monitoring', 'desktop-ai', 'user-actions'], verticals: [], plainDescription: 'Monitors everything you do on your computer and uses AI to suggest ways to work more efficiently.', relatedExamples: ['OSpipe'], primaryFor: [] },
    ],
  },
  {
    id: 'robotics',
    description: 'ROS3 + cognitive robotics',
    primaryCrate: 'agentic-robotics-core',
    status: 'experimental',
    docPath: 'docs/robotics.md',
    keywords: ['robotics', 'ros', 'robot', 'embedded', 'real-time', 'perception', 'motor', 'sensor'],
    problemStatement: 'I need cognitive robotics / ROS integration / real-time perception',
    synonyms: ['robot control', 'autonomous systems', 'sensor fusion'],
    relatedCapabilities: ['nervous_system', 'attention_mechanisms'],
    technologies: [
      { id: 'agentic-robotics', name: 'Agentic Robotics', crate: 'agentic-robotics-core', capabilityId: 'robotics', complexity: null, latency: null, status: 'experimental', useWhen: 'ROS3, Zenoh, cognitive robotics with perception pipeline', features: null, deploymentTargets: ['native', 'embedded'], sourcePath: 'crates/agentic-robotics-core', algorithms: [], useCases: [], problemDomains: ['robotics', 'perception'], verticals: ['robotics'], plainDescription: 'A cognitive robotics framework with ROS3 integration for autonomous systems.', relatedExamples: ['robotics'], primaryFor: ['cognitive-robotics'] },
    ],
  },
  {
    id: 'financial',
    description: 'Coherence-gated trading signals',
    primaryCrate: 'neural-trader-core',
    status: 'experimental',
    docPath: 'docs/financial.md',
    keywords: ['trading', 'financial', 'market', 'signal', 'neural trader', 'coherence', 'audit'],
    problemStatement: 'I need AI-powered trading signals / financial coherence gates',
    synonyms: ['algorithmic trading', 'market signals', 'trading AI'],
    relatedCapabilities: ['coherence_safety'],
    technologies: [
      { id: 'neural-trader', name: 'Neural Trader', crate: 'neural-trader-core', capabilityId: 'financial', complexity: null, latency: null, status: 'experimental', useWhen: 'coherence-gated trading with MinCut gate, CUSUM drift, proof-gated mutation', features: null, deploymentTargets: ['native', 'wasm'], sourcePath: 'crates/neural-trader-core', algorithms: [], useCases: [], problemDomains: ['trading', 'financial-signals'], verticals: ['finance'], plainDescription: 'AI trading signals that are fact-checked by coherence gates before execution.', relatedExamples: ['neural-trader'], primaryFor: ['coherence-gated-trading'] },
    ],
  },
];
