// ruvector-catalog — Technology recommender for the RuVector monorepo
// https://github.com/ruvnet/ruvector
// Capabilities 1-3: Fully enriched with V3 fields (ADR-008)

import type { Capability } from '../types/index.js';

export const ENRICHED_CAPABILITIES: Capability[] = [
  // ───────────────────────────────────────────────────────────
  // 1. Vector Search (FULLY ENRICHED)
  // ───────────────────────────────────────────────────────────
  {
    id: 'vector_search',
    description: 'Sub-millisecond nearest-neighbor search',
    primaryCrate: 'ruvector-core',
    status: 'production',
    docPath: 'docs/vector_search.md',
    keywords: ['search', 'similarity', 'nearest neighbor', 'embedding', 'vector', 'hnsw', 'index', 'query', 'retrieval', 'rag', 'semantic search'],
    problemStatement: 'I need fast similarity search / nearest-neighbor lookup / semantic retrieval',
    synonyms: ['find similar items', 'vector database', 'embedding search', 'RAG retrieval', 'recommendation engine'],
    relatedCapabilities: ['graph_intelligence', 'storage', 'llm_runtime'],
    technologies: [
      {
        id: 'hnsw', name: 'HNSW', crate: 'ruvector-core', capabilityId: 'vector_search',
        complexity: 'O(log n)', latency: '61us p50', status: 'production',
        useWhen: 'general-purpose nearest neighbor search',
        features: 'simd,memory-only,hnsw',
        deploymentTargets: ['native', 'wasm', 'nodejs'],
        sourcePath: 'crates/ruvector-core',
        algorithms: [{ name: 'HNSW', technologyId: 'hnsw', crate: 'ruvector-core', complexity: 'O(log n)', description: 'Hierarchical Navigable Small World graph for approximate nearest neighbor' }],
        useCases: ['Find similar documents or images in a large collection', 'Power a recommendation engine with sub-millisecond latency', 'Build a RAG pipeline that retrieves relevant context for an LLM'],
        problemDomains: ['similarity-search', 'retrieval', 'recommendation'],
        verticals: ['healthcare', 'genomics'],
        plainDescription: 'The fastest way to find similar items in a large dataset, like a search engine for meaning rather than keywords.',
        relatedExamples: ['OSpipe', 'refrag-pipeline', 'wasm-react', 'edge'],
        primaryFor: ['vector-search', 'similarity-search', 'nearest-neighbor'],
      },
      {
        id: 'hyperbolic-hnsw', name: 'Hyperbolic HNSW', crate: 'ruvector-hyperbolic-hnsw', capabilityId: 'vector_search',
        complexity: 'O(log n)', latency: null, status: 'production',
        useWhen: 'hierarchical data (taxonomies, trees, ontologies)',
        features: null,
        deploymentTargets: ['native', 'wasm'],
        sourcePath: 'crates/ruvector-hyperbolic-hnsw',
        algorithms: [],
        useCases: ['Search a product taxonomy where categories have sub-categories', 'Navigate an ontology or knowledge graph with tree-like structure', 'Find similar items in datasets with inherent hierarchy'],
        problemDomains: ['hierarchical-search', 'taxonomy', 'ontology'],
        verticals: ['healthcare', 'genomics'],
        plainDescription: 'A search engine tuned for tree-shaped data like medical taxonomies or product catalogs.',
        relatedExamples: [],
        primaryFor: ['hierarchical-search'],
      },
      {
        id: 'diskann', name: 'DiskANN/Vamana', crate: 'ruvector-core', capabilityId: 'vector_search',
        complexity: null, latency: null, status: 'experimental',
        useWhen: 'billion-scale SSD-backed datasets',
        features: null,
        deploymentTargets: ['native'],
        sourcePath: 'crates/ruvector-core',
        algorithms: [],
        useCases: ['Search billions of vectors without fitting them all in RAM', 'Build a web-scale image search that runs on SSDs'],
        problemDomains: ['large-scale-search', 'disk-based'],
        verticals: [],
        plainDescription: 'Search billions of items using your hard drive instead of expensive RAM.',
        relatedExamples: [],
        primaryFor: [],
      },
      {
        id: 'colbert', name: 'ColBERT', crate: 'ruvector-core', capabilityId: 'vector_search',
        complexity: null, latency: null, status: 'production',
        useWhen: 'late interaction retrieval with per-token embeddings',
        features: null,
        deploymentTargets: ['native', 'wasm'],
        sourcePath: 'crates/ruvector-core',
        algorithms: [],
        useCases: ['High-quality document retrieval where every word matters', 'Build a search system that understands passages, not just whole documents'],
        problemDomains: ['document-retrieval', 'passage-search'],
        verticals: ['healthcare'],
        plainDescription: 'A smarter document search that compares individual words for higher accuracy.',
        relatedExamples: [],
        primaryFor: [],
      },
      {
        id: 'neural-hashing', name: 'Neural Hashing', crate: 'ruvector-core', capabilityId: 'vector_search',
        complexity: null, latency: null, status: 'production',
        useWhen: '32x compression needed for large corpora',
        features: null,
        deploymentTargets: ['native', 'wasm'],
        sourcePath: 'crates/ruvector-core',
        algorithms: [],
        useCases: ['Compress a large embedding index to fit in memory', 'Run similarity search on a device with limited storage'],
        problemDomains: ['compression', 'memory-efficient-search'],
        verticals: ['edge-iot'],
        plainDescription: 'Shrinks your search index by 32x so it fits on smaller devices.',
        relatedExamples: [],
        primaryFor: [],
      },
      {
        id: 'micro-hnsw', name: 'Micro HNSW', crate: 'micro-hnsw-wasm', capabilityId: 'vector_search',
        complexity: 'O(log n)', latency: null, status: 'experimental',
        useWhen: 'ultra-constrained edge/IoT (11.8KB WASM)',
        features: null,
        deploymentTargets: ['wasm'],
        sourcePath: 'crates/micro-hnsw-wasm',
        algorithms: [],
        useCases: ['Run vector search on a microcontroller or tiny IoT sensor', 'Add search to an embedded device with kilobytes of memory'],
        problemDomains: ['edge-search', 'iot', 'ultra-lightweight'],
        verticals: ['edge-iot'],
        plainDescription: 'The smallest possible vector search engine, fits in just 12KB for tiny devices.',
        relatedExamples: ['spiking-network', 'edge'],
        primaryFor: ['edge-vector-search'],
      },
      {
        id: 'hybrid-search', name: 'Hybrid Search', crate: 'ruvector-core', capabilityId: 'vector_search',
        complexity: null, latency: null, status: 'production',
        useWhen: 'combining keyword + semantic search with RRF fusion',
        features: null,
        deploymentTargets: ['native', 'wasm', 'nodejs'],
        sourcePath: 'crates/ruvector-core',
        algorithms: [],
        useCases: ['Combine keyword matching with semantic understanding for best results', 'Build a search that handles both exact terms and fuzzy meaning'],
        problemDomains: ['hybrid-retrieval', 'search-fusion'],
        verticals: ['healthcare'],
        plainDescription: 'Best-of-both-worlds search: finds things by keywords AND by meaning.',
        relatedExamples: ['refrag-pipeline'],
        primaryFor: [],
      },
      {
        id: 'matryoshka', name: 'Matryoshka Embeddings', crate: 'ruvector-core', capabilityId: 'vector_search',
        complexity: null, latency: null, status: 'production',
        useWhen: 'variable-dimension embeddings for adaptive precision',
        features: null,
        deploymentTargets: ['native', 'wasm'],
        sourcePath: 'crates/ruvector-core',
        algorithms: [],
        useCases: ['Trade off search quality vs speed by adjusting embedding dimensions at query time', 'Use coarse search for speed, then refine with full dimensions'],
        problemDomains: ['adaptive-search', 'multi-resolution'],
        verticals: [],
        plainDescription: 'Nested embeddings that let you choose between speed and accuracy on the fly.',
        relatedExamples: [],
        primaryFor: [],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────
  // 2. Graph Intelligence (FULLY ENRICHED)
  // ───────────────────────────────────────────────────────────
  {
    id: 'graph_intelligence',
    description: 'Graph database, GNN, knowledge graphs',
    primaryCrate: 'ruvector-graph',
    status: 'production',
    docPath: 'docs/graph_intelligence.md',
    keywords: ['graph', 'relationship', 'knowledge', 'pagerank', 'community', 'neo4j', 'cypher', 'gnn', 'neural network', 'dag', 'causal'],
    problemStatement: 'I need to model relationships / build a knowledge graph / analyze network structure',
    synonyms: ['graph database', 'connected data', 'find communities', 'relationship mapping', 'social network analysis'],
    relatedCapabilities: ['vector_search', 'attention_mechanisms', 'mincut'],
    technologies: [
      {
        id: 'hypergraph-db', name: 'Hypergraph DB', crate: 'ruvector-graph', capabilityId: 'graph_intelligence',
        complexity: null, latency: null, status: 'production',
        useWhen: 'graph database with 230+ SQL functions and Cypher',
        features: 'distributed,federation,fulltext,geospatial,temporal',
        deploymentTargets: ['native', 'wasm', 'nodejs'],
        sourcePath: 'crates/ruvector-graph',
        algorithms: [
          { name: 'PageRank', technologyId: 'hypergraph-db', crate: 'ruvector-graph', complexity: null, description: 'Graph centrality ranking' },
          { name: 'Louvain', technologyId: 'hypergraph-db', crate: 'ruvector-graph', complexity: null, description: 'Community detection' },
          { name: 'Dijkstra', technologyId: 'hypergraph-db', crate: 'ruvector-graph', complexity: 'O(V log V + E)', description: 'Shortest path' },
        ],
        useCases: ['Store and query a knowledge graph with millions of relationships', 'Find the most influential nodes in a social or citation network', 'Detect communities and clusters in connected data'],
        problemDomains: ['knowledge-graph', 'graph-database', 'network-analysis'],
        verticals: ['healthcare', 'finance'],
        plainDescription: 'A graph database that stores relationships between things and answers questions like "who is connected to whom" and "what is most important."',
        relatedExamples: [],
        primaryFor: ['knowledge-graph', 'graph-database'],
      },
      {
        id: 'gnn', name: 'Graph Neural Networks', crate: 'ruvector-gnn', capabilityId: 'graph_intelligence',
        complexity: null, latency: null, status: 'production',
        useWhen: 'learning on graph-structured data (GCN, GAT, GraphSAGE)',
        features: null,
        deploymentTargets: ['native', 'wasm', 'nodejs'],
        sourcePath: 'crates/ruvector-gnn',
        algorithms: [
          { name: 'GCN', technologyId: 'gnn', crate: 'ruvector-gnn', complexity: null, description: 'Graph Convolutional Network' },
          { name: 'GAT', technologyId: 'gnn', crate: 'ruvector-gnn', complexity: null, description: 'Graph Attention Network' },
          { name: 'GraphSAGE', technologyId: 'gnn', crate: 'ruvector-gnn', complexity: null, description: 'Inductive graph learning' },
        ],
        useCases: ['Predict properties of molecules from their atomic graph structure', 'Classify nodes in a social network based on their connections', 'Learn embeddings from graph-structured data for downstream tasks'],
        problemDomains: ['graph-learning', 'node-classification', 'link-prediction'],
        verticals: ['healthcare', 'genomics'],
        plainDescription: 'AI that learns patterns from connected data, like predicting drug interactions from molecular graphs.',
        relatedExamples: [],
        primaryFor: ['graph-neural-network'],
      },
      {
        id: 'graph-transformer', name: 'Graph Transformer', crate: 'ruvector-graph-transformer', capabilityId: 'graph_intelligence',
        complexity: null, latency: null, status: 'production',
        useWhen: '8-module proof-gated transformer on graphs',
        features: null,
        deploymentTargets: ['native', 'wasm', 'nodejs'],
        sourcePath: 'crates/ruvector-graph-transformer',
        algorithms: [],
        useCases: ['Run transformer-style reasoning over graph structures', 'Combine graph topology with attention for richer representations'],
        problemDomains: ['graph-reasoning', 'transformer'],
        verticals: [],
        plainDescription: 'A transformer that reasons over connected data, combining graph structure with attention.',
        relatedExamples: [],
        primaryFor: [],
      },
      {
        id: 'causal-dag', name: 'Causal DAG', crate: 'ruvector-dag', capabilityId: 'graph_intelligence',
        complexity: null, latency: null, status: 'production',
        useWhen: 'DAG query optimization, causal inference',
        features: null,
        deploymentTargets: ['native', 'wasm'],
        sourcePath: 'crates/ruvector-dag',
        algorithms: [],
        useCases: ['Determine cause-and-effect relationships from observational data', 'Optimize query execution plans using directed acyclic graphs'],
        problemDomains: ['causal-inference', 'dag-optimization'],
        verticals: ['healthcare'],
        plainDescription: 'Figures out cause-and-effect relationships, like which treatment actually helped a patient.',
        relatedExamples: [],
        primaryFor: [],
      },
      {
        id: 'graph-sparsifier', name: 'Graph Sparsification', crate: 'ruvector-sparsifier', capabilityId: 'graph_intelligence',
        complexity: null, latency: null, status: 'production',
        useWhen: 'spectral sparsification preserving Laplacian properties',
        features: null,
        deploymentTargets: ['native', 'wasm'],
        sourcePath: 'crates/ruvector-sparsifier',
        algorithms: [],
        useCases: ['Simplify a massive graph while preserving its essential structure', 'Speed up graph algorithms by reducing edge count'],
        problemDomains: ['graph-compression', 'spectral'],
        verticals: [],
        plainDescription: 'Simplifies large graphs while keeping their important properties intact.',
        relatedExamples: [],
        primaryFor: [],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────
  // 3. Attention Mechanisms (FULLY ENRICHED)
  // ───────────────────────────────────────────────────────────
  {
    id: 'attention_mechanisms',
    description: '18+ attention variants for transformers and beyond',
    primaryCrate: 'ruvector-attention',
    status: 'production',
    docPath: 'docs/attention_mechanisms.md',
    keywords: ['attention', 'transformer', 'sequence', 'token', 'flash', 'mamba', 'moe', 'mixture of experts', 'multi-head', 'self-attention'],
    problemStatement: 'I need attention mechanisms / transformer building blocks / sequence modeling',
    synonyms: ['build a transformer', 'process long sequences', 'mixture of experts', 'efficient attention'],
    relatedCapabilities: ['graph_intelligence', 'self_learning', 'nervous_system'],
    technologies: [
      {
        id: 'flash-attention', name: 'FlashAttention-3', crate: 'ruvector-attention', capabilityId: 'attention_mechanisms',
        complexity: 'O(n) memory', latency: null, status: 'production',
        useWhen: 'memory-efficient attention for long sequences',
        features: null,
        deploymentTargets: ['native', 'wasm', 'nodejs'],
        sourcePath: 'crates/ruvector-attention',
        algorithms: [{ name: 'FlashAttention-3', technologyId: 'flash-attention', crate: 'ruvector-attention', complexity: 'O(n^2) compute, O(n) memory', description: 'IO-aware exact attention' }],
        useCases: ['Process long documents without running out of GPU memory', 'Speed up transformer inference by 2-7x with tiled attention', 'Build custom LLMs that handle 100K+ token contexts'],
        problemDomains: ['attention', 'memory-efficiency', 'long-context'],
        verticals: [],
        plainDescription: 'Makes transformer attention fast and memory-efficient, so models can read much longer documents.',
        relatedExamples: [],
        primaryFor: ['efficient-attention', 'long-context'],
      },
      {
        id: 'mamba-s5', name: 'Mamba S5', crate: 'ruvector-attention', capabilityId: 'attention_mechanisms',
        complexity: 'O(n)', latency: null, status: 'production',
        useWhen: 'linear-time sequence modeling',
        features: null,
        deploymentTargets: ['native', 'wasm'],
        sourcePath: 'crates/ruvector-attention',
        algorithms: [],
        useCases: ['Model very long sequences where quadratic attention is too expensive', 'Build a state-space model for time-series or audio processing'],
        problemDomains: ['sequence-modeling', 'state-space', 'linear-time'],
        verticals: [],
        plainDescription: 'A linear-time alternative to attention that handles very long sequences efficiently.',
        relatedExamples: [],
        primaryFor: ['linear-attention', 'state-space-models'],
      },
      {
        id: 'moe-attention', name: 'MoE Attention', crate: 'ruvector-attention', capabilityId: 'attention_mechanisms',
        complexity: 'O(n*k*expert)', latency: '<10us routing', status: 'production',
        useWhen: 'mixture-of-experts with memory-aware routing',
        features: null,
        deploymentTargets: ['native', 'wasm'],
        sourcePath: 'crates/ruvector-attention',
        algorithms: [],
        useCases: ['Route different queries to specialized expert networks', 'Scale model capacity without scaling compute proportionally'],
        problemDomains: ['mixture-of-experts', 'routing', 'scaling'],
        verticals: [],
        plainDescription: 'Sends each query to the best specialist, like a hospital triage system for AI.',
        relatedExamples: [],
        primaryFor: ['mixture-of-experts'],
      },
      {
        id: 'sheaf-attention', name: 'Sheaf Attention', crate: 'ruvector-attention', capabilityId: 'attention_mechanisms',
        complexity: 'O(n^2)', latency: null, status: 'production',
        useWhen: 'algebraic topology, restriction maps, consistency checking',
        features: null,
        deploymentTargets: ['native', 'wasm'],
        sourcePath: 'crates/ruvector-attention',
        algorithms: [],
        useCases: ['Check consistency of information across overlapping data sources', 'Apply topological methods to attention for richer representations'],
        problemDomains: ['topology', 'consistency', 'algebraic'],
        verticals: [],
        plainDescription: 'Attention that checks whether different data sources agree with each other using advanced math.',
        relatedExamples: ['prime-radiant'],
        primaryFor: [],
      },
      {
        id: 'mincut-gated', name: 'Min-Cut Gated Attention', crate: 'ruvector-attn-mincut', capabilityId: 'attention_mechanisms',
        complexity: 'O(n*E)', latency: null, status: 'production',
        useWhen: 'graph-based gating replacing softmax',
        features: null,
        deploymentTargets: ['native', 'wasm'],
        sourcePath: 'crates/ruvector-attn-mincut',
        algorithms: [{ name: "Dinic's max-flow", technologyId: 'mincut-gated', crate: 'ruvector-attn-mincut', complexity: 'O(V^2*E)', description: 'Maximum flow for graph partitioning' }],
        useCases: ['Replace softmax with graph-based gating for more interpretable attention', 'Partition attention into meaningful clusters'],
        problemDomains: ['graph-attention', 'interpretability'],
        verticals: [],
        plainDescription: 'An alternative to standard attention that uses graph cuts for more interpretable results.',
        relatedExamples: [],
        primaryFor: [],
      },
      {
        id: 'hyperbolic-attention', name: 'Hyperbolic Attention', crate: 'ruvector-attention', capabilityId: 'attention_mechanisms',
        complexity: 'O(n^2)', latency: null, status: 'production',
        useWhen: 'Poincare ball geometry for hierarchical attention',
        features: null,
        deploymentTargets: ['native', 'wasm'],
        sourcePath: 'crates/ruvector-attention',
        algorithms: [],
        useCases: ['Attend to hierarchically organized data more naturally', 'Capture tree-like dependencies in attention patterns'],
        problemDomains: ['hierarchical-attention', 'hyperbolic-geometry'],
        verticals: [],
        plainDescription: 'Attention that naturally understands tree-like hierarchies in data.',
        relatedExamples: [],
        primaryFor: [],
      },
      {
        id: 'topology-gated', name: 'Topology-Gated Attention', crate: 'ruvector-attention', capabilityId: 'attention_mechanisms',
        complexity: null, latency: null, status: 'experimental',
        useWhen: '3-mode policy (stable/cautious/freeze) with coherence',
        features: null,
        deploymentTargets: ['native', 'wasm'],
        sourcePath: 'crates/ruvector-attention',
        algorithms: [],
        useCases: ['Build attention that adapts its behavior based on data topology', 'Freeze attention patterns when coherence drops below threshold'],
        problemDomains: ['adaptive-attention', 'topology'],
        verticals: [],
        plainDescription: 'Attention that slows down or freezes when it detects something might be wrong.',
        relatedExamples: [],
        primaryFor: [],
      },
      {
        id: 'spiking-graph-attention', name: 'Spiking Graph Attention', crate: 'ruvector-attention', capabilityId: 'attention_mechanisms',
        complexity: 'O(spikes)', latency: null, status: 'experimental',
        useWhen: 'event-driven, energy-efficient graph attention',
        features: null,
        deploymentTargets: ['native', 'wasm'],
        sourcePath: 'crates/ruvector-attention',
        algorithms: [],
        useCases: ['Run attention on neuromorphic hardware with minimal energy', 'Process event-driven data streams with spike-based graph attention'],
        problemDomains: ['neuromorphic', 'energy-efficient', 'event-driven'],
        verticals: ['edge-iot', 'robotics'],
        plainDescription: 'Brain-inspired attention that only fires when needed, saving energy on edge devices.',
        relatedExamples: ['spiking-network'],
        primaryFor: [],
      },
    ],
  },
];
