// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRecord } from "./AgentRecord";
import type { AgentRemovedPayload } from "./AgentRemovedPayload";
import type { CommunicationPayload } from "./CommunicationPayload";
import type { DeltaPayload } from "./DeltaPayload";
import type { HeartbeatPayload } from "./HeartbeatPayload";
import type { SnapshotPayload } from "./SnapshotPayload";

/**
 * Top-level telemetry envelope arriving on `/ws/agent-telemetry`.
 *
 * Discriminated union by `type`; payload shape varies. Producers always
 * emit `schema_version` at the envelope root so consumers can reject
 * unsupported versions before parsing the payload.
 */
export type AgentTelemetryEnvelope = { schema_version: number, 
/**
 * agentbox session UUID. Constant for the lifetime of one WS connection.
 */
session_id: string, 
/**
 * Monotonically increasing frame counter, per session.
 */
frame_id: bigint, 
/**
 * Unix milliseconds at frame emission.
 */
timestamp_ms: bigint, } & ({ "type": "snapshot", "payload": SnapshotPayload } | { "type": "delta", "payload": DeltaPayload } | { "type": "agent_added", "payload": AgentRecord } | { "type": "agent_removed", "payload": AgentRemovedPayload } | { "type": "heartbeat", "payload": HeartbeatPayload } | { "type": "communication", "payload": CommunicationPayload });
