// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionKind } from "./ActionKind";
import type { ModifierKeys } from "./ModifierKeys";
import type { NodeClass } from "./NodeClass";
import type { WorldPosition } from "./WorldPosition";

/**
 * Payload for an `agent-action` envelope at schema version 1.
 *
 * Fields match the canonical TypeScript schema in
 * `_resolutions/T4-T6-T7-api-contracts.md` §T7 byte-for-byte (serde rename
 * rules below preserve the wire shape).
 */
export type AgentAction = { 
/**
 * Schema version. Bumped per ADR-10 §D8 when payload semantics change.
 */
schema_version: number, 
/**
 * UUID v4, generated per click. Receivers MAY use this for dedup.
 */
message_id: string, 
/**
 * Unix milliseconds at click time.
 */
issued_at_ms: bigint, 
/**
 * Pubkey of the clicking user, npub format. Informational only —
 * the receiver verifies authorisation via its own bridge session.
 */
issued_by_pubkey: string, 
/**
 * Action kind. Forward-compatible: receivers ignore unknown variants
 * (serde tolerates this only on the consumer side via
 * `#[serde(other)]` adapters; producers emit only the variants below).
 */
kind: ActionKind, 
/**
 * Agent identity. Required for every kind.
 */
agent_id: string, 
/**
 * Swarm identity, when known. Not all agents belong to swarms.
 */
swarm_id: string | null, 
/**
 * Class flag bits from the V3 node id (ADR-07 §D3 + ADR-08 §D6).
 * Lets the receiver short-circuit if the click target is not actually
 * an agent.
 */
node_class: NodeClass, 
/**
 * Click modifiers, for receivers that distinguish primary / secondary
 * actions. All inner flags optional; absent struct defaults to primary
 * semantics.
 */
modifiers: ModifierKeys | null, 
/**
 * Cursor in scene world-space at click time. Used by the receiver to
 * position popovers when rendering inside the same browser tab.
 */
cursor_world_position: WorldPosition | null, 
/**
 * Bridge session id from the ADR-10 §D4 auth flow. Receivers MAY use
 * this to correlate the click with the bridge session that issued the
 * `Authorization` for the originating VisionClaw tab.
 */
bridge_id: string | null, };
