// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommunicationPayload = { from_agent_id: string, to_agent_id: string, weight: number, };
