// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MembershipChangePayload } from "./MembershipChangePayload";
import type { RoleChangePayload } from "./RoleChangePayload";
import type { SessionRevokedPayload } from "./SessionRevokedPayload";

/**
 * Three normative event kinds. Adjacent serde shape: `{"type": "...",
 * "payload": { ... }}` matching ADR-10 §D5 verbatim.
 */
export type EnterpriseEventKind = { "type": "membership_change", "payload": MembershipChangePayload } | { "type": "role_change", "payload": RoleChangePayload } | { "type": "session_revoked", "payload": SessionRevokedPayload };
