// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse-grained RBAC label. Maps to UI affordances; finer-grained
 * permission checks happen in the forum, not VisionFlow.
 */
export type EnterpriseRole = "reader" | "operator" | "admin";
