// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MembershipAction } from "./MembershipAction";

export type MembershipChangePayload = { 
/**
 * Nostr public key in npub bech32 form.
 */
npub: string, 
/**
 * Org/workspace identifier.
 */
org_id: string, action: MembershipAction, };
