// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Modifier-key state at click time. All fields default to `false` (primary
 * click semantics with no modifiers).
 */
export type ModifierKeys = { ctrl: boolean, shift: boolean, alt: boolean, meta: boolean, 
/**
 * 0 = primary, 1 = middle, 2 = secondary. Absent => primary.
 */
button: number | null, };
