// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Class flag bits derived from the V3 node id, projected onto the small set
 * of receiver-actionable categories. Receivers ignore the full ontology
 * taxonomy; only agent vs. non-agent matters at click time.
 *
 * Wire encoding is `snake_case`. Underlying bit layout owned by ADR-08 §D6.
 */
export type NodeClass = "knowledge_page" | "ontology_class" | "ontology_property" | "axiom" | "agent" | "linked_page";
