// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of the GitHub adapter for one source file.
 *
 * The domain receives this via `IngestPage` / `IngestOntologyOnly`
 * commands and never sees raw HTTP responses, `octocrab` types, or
 * Logseq-specific frontmatter / wikilink syntax. If the corpus migrates
 * off Logseq, only the adapter changes; this value object stays stable.
 *
 * `frontmatter_json` and `jsonld_blocks` are deliberately `serde_json::Value`
 * because:
 *
 * - Frontmatter is open-ended (Logseq accepts arbitrary keys + tag lists).
 * - JSON-LD blocks must round-trip without loss for the ontology parser.
 *
 * The richer DDD-08 fields (`prose_blocks`, `ontology_blocks`,
 * `outbound_wikilinks`) are domain projections built *from* this raw shape;
 * they belong in the Section 8 parser, not in this cross-boundary contract.
 */
export type ParsedMarkdown = { 
/**
 * Repo-relative path, normalised to forward slashes.
 * (Section 8 calls this `path`; we use `canonical_path` to make the
 * normalisation guarantee explicit at the boundary.)
 */
canonical_path: string, 
/**
 * Raw file body, UTF-8.
 */
raw: string, 
/**
 * Parsed Logseq frontmatter as a JSON object. Keys preserved verbatim
 * except for `public:: true` which the adapter normalises into
 * `{"public": true}` per DDD-08 §"To Section 10".
 */
frontmatter_json: Record<string, unknown>, 
/**
 * `### OntologyBlock` JSON-LD bodies, one per block. Order preserved.
 */
jsonld_blocks: Array<Record<string, unknown>>, 
/**
 * Git blob SHA1 (40 hex chars). Used by the SHA1-gated sync.
 */
commit_sha: string, };
