// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionRevokedPayload = { 
/**
 * The bridge session UUID (ADR-10 §D4) that the forum invalidated.
 */
bridge_id: string, };
