// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRecord } from "./AgentRecord";

export type SnapshotPayload = { agents: Array<AgentRecord>, };
