// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cursor world-space position. `f64` on the wire to match the canonical
 * TypeScript `number` semantics (IEEE-754 double-precision). The renderer
 * downcasts to `f32` internally; the contract leaves precision to the
 * receiver.
 */
export type WorldPosition = { x: number, y: number, z: number, };
